use bib_model::{
    BibConfigurationBuilder, BibSourceLocation, COMPATIBILITY_VERSION, DataList, DataListId,
    DataListKind, DateValue, EntryBuilder, EntryId, EntryType, Field, FieldId, FieldProvenance,
    FieldValue, FieldValueStage, Literal, NameBuilder, NameList, NamePartValue, OutputFormat,
    OutputNewline, OutputRequest, ProcessedBibliographyBuilder, ProcessedSectionBuilder, Range,
    RangeEndpoint, SectionId, SourceSpan, Uri, Verbatim, VirtualPath,
};
use bib_unicode::{LegacyEncoding, UnicodeData};

use crate::{
    BblOutputFailureKind, BblSerializer, BblXmlSerializer, BibLatexXmlSerializer, BibtexMacro,
    BibtexOptions, BibtexOutputFailureKind, BibtexSerializer, OutputContext, Serializer,
    XmlOutputFailureKind, XmlSchemaKind, generate_xml_schema,
};

fn source() -> BibSourceLocation {
    BibSourceLocation::new(
        VirtualPath::user("full-bbl.bib").expect("valid test path"),
        SourceSpan {
            byte_start: 0,
            byte_end: 1,
            line: 1,
            column: 1,
        },
    )
    .expect("valid test source")
}

fn provenance() -> FieldProvenance {
    FieldProvenance::Datasource(source())
}

fn field(id: &str, value: FieldValue) -> Field {
    Field::new(
        FieldId::new(id).expect("valid field id"),
        value,
        FieldValueStage::Computed,
        provenance(),
    )
}

fn document_with_entry(entry: bib_model::Entry) -> bib_model::ProcessedBibliography {
    let entry_id = entry.id().clone();
    let mut section = ProcessedSectionBuilder::new(SectionId::new(0));
    section.entry(entry).expect("unique entry");
    section
        .list(
            DataList::new(
                DataListId::new("main/global//global/global/global").expect("valid list"),
                [entry_id],
            )
            .expect("valid data list"),
        )
        .expect("known entry");
    let mut document = ProcessedBibliographyBuilder::new(
        BibConfigurationBuilder::new(COMPATIBILITY_VERSION).freeze(),
    );
    document.section(section.freeze()).expect("unique section");
    document.freeze()
}

fn request() -> OutputRequest {
    OutputRequest::new(
        VirtualPath::user("main.bbl").expect("valid output path"),
        OutputFormat::Bbl,
    )
}

fn serialize(
    document: &bib_model::ProcessedBibliography,
    request: &OutputRequest,
) -> Result<bib_model::GeneratedFile, crate::BblOutputFailure> {
    BblSerializer.serialize(
        OutputContext::new(document, &UnicodeData::pinned()),
        request,
    )
}

fn bibtex_request() -> OutputRequest {
    OutputRequest::new(
        VirtualPath::user("main.bib").expect("valid output path"),
        OutputFormat::Bibtex,
    )
}

fn person(family: &str, given: &str) -> bib_model::Name {
    let mut name = NameBuilder::new();
    name.family(Literal::new(family));
    name.given(Literal::new(given));
    name.freeze().expect("complete name")
}

fn add_field(entry: &mut EntryBuilder, name: &str, value: FieldValue) {
    entry
        .field(
            FieldId::new(name).expect("valid field"),
            value,
            FieldValueStage::Computed,
            provenance(),
        )
        .expect("unique field");
}

fn add_literal(entry: &mut EntryBuilder, name: &str, value: &str) {
    add_field(entry, name, FieldValue::Literal(Literal::new(value)));
}

#[test]
fn biblatexml_is_exact_and_escapes_xml() {
    let mut entry = EntryBuilder::new(
        EntryId::new("A&1").expect("valid entry"),
        EntryType::new("book").expect("valid type"),
        source(),
    );
    add_literal(&mut entry, "title", "Š <Title> & more");
    let document = document_with_entry(entry.freeze());
    let request = OutputRequest::new(
        VirtualPath::user("tool.bltxml").expect("valid path"),
        OutputFormat::BibLatexXml,
    );
    let output = BibLatexXmlSerializer
        .serialize(
            OutputContext::new(&document, &UnicodeData::pinned()),
            &request,
        )
        .expect("serializes");
    assert_eq!(
        std::str::from_utf8(output.bytes()).expect("UTF-8"),
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<?xml-model href=\"tool.rng\" type=\"application/xml\" schematypens=\"http://relaxng.org/ns/structure/1.0\"?>\n<!-- Auto-generated by Biber::Output::biblatexml -->\n\n<bltx:entries xmlns:bltx=\"http://biblatex-biber.sourceforge.net/biblatexml\">\n  <bltx:entry id=\"A&amp;1\" entrytype=\"book\">\n    <bltx:title>Š &lt;Title&gt; &amp; more</bltx:title>\n  </bltx:entry>\n</bltx:entries>\n"
    );
}

#[test]
fn bblxml_is_exact_for_detached_list() {
    let mut entry = EntryBuilder::new(
        EntryId::new("key").expect("valid entry"),
        EntryType::new("book").expect("valid type"),
        source(),
    );
    add_literal(&mut entry, "title", "A title");
    let document = document_with_entry(entry.freeze());
    let request = OutputRequest::new(
        VirtualPath::user("main.bblxml").expect("valid path"),
        OutputFormat::BblXml,
    );
    let output = BblXmlSerializer
        .serialize(
            OutputContext::new(&document, &UnicodeData::pinned()),
            &request,
        )
        .expect("serializes");
    let text = std::str::from_utf8(output.bytes()).expect("UTF-8");
    assert!(text.contains(
        "<bbl:refsections xmlns:bbl=\"https://sourceforge.net/projects/biblatex/bblxml\">"
    ));
    assert!(text.contains("<bbl:field name=\"title\">A title</bbl:field>"));
    assert!(text.ends_with("</bbl:refsections>\n"));
}

#[test]
fn xml_encoding_newlines_limits_and_wrong_format_are_typed() {
    let mut entry = EntryBuilder::new(
        EntryId::new("typed").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    add_literal(&mut entry, "title", "café");
    let document = document_with_entry(entry.freeze());
    let latin = OutputRequest::new(
        VirtualPath::user("typed.bltxml").expect("valid path"),
        OutputFormat::BibLatexXml,
    )
    .with_encoding(LegacyEncoding::Latin1)
    .with_newline(OutputNewline::CrLf);
    let output = BibLatexXmlSerializer
        .serialize(
            OutputContext::new(&document, &UnicodeData::pinned()),
            &latin,
        )
        .expect("Latin-1");
    assert!(output.bytes().windows(2).any(|pair| pair == b"\r\n"));
    let encoding = b"encoding=\"ISO-8859-1";
    assert!(
        output
            .bytes()
            .windows(encoding.len())
            .any(|part| part == encoding)
    );
    let wrong = OutputRequest::new(
        VirtualPath::user("bad.bbl").expect("path"),
        OutputFormat::Bbl,
    );
    assert_eq!(
        BibLatexXmlSerializer
            .serialize(
                OutputContext::new(&document, &UnicodeData::pinned()),
                &wrong
            )
            .expect_err("wrong format")
            .kind(),
        XmlOutputFailureKind::WrongFormat
    );
    assert_eq!(
        BibLatexXmlSerializer
            .serialize(
                OutputContext::new(&document, &UnicodeData::pinned()),
                &latin.clone().with_max_bytes(8)
            )
            .expect_err("limit")
            .kind(),
        XmlOutputFailureKind::Limit
    );
}

#[test]
fn generated_xml_schema_is_sorted_and_deterministic() {
    let mut entry = EntryBuilder::new(
        EntryId::new("schema").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    add_literal(&mut entry, "zeta", "z");
    add_literal(&mut entry, "alpha", "a");
    let document = document_with_entry(entry.freeze());
    let request = OutputRequest::new(
        VirtualPath::user("schema.rng").expect("path"),
        OutputFormat::BibLatexXml,
    );
    let output = generate_xml_schema(
        OutputContext::new(&document, &UnicodeData::pinned()),
        &request,
        XmlSchemaKind::BibLatex,
    )
    .expect("schema");
    let text = std::str::from_utf8(output.bytes()).expect("UTF-8");
    assert!(
        text.find("name=\"alpha\"").expect("schema field exists")
            < text.find("name=\"zeta\"").expect("schema field exists")
    );
    assert_eq!(
        output,
        generate_xml_schema(
            OutputContext::new(&document, &UnicodeData::pinned()),
            &request,
            XmlSchemaKind::BibLatex
        )
        .expect("same schema")
    );
}

#[test]
fn full_bbl_fixture_is_byte_exact() {
    let mut name = NameBuilder::new();
    name.family_part(NamePartValue::new(
        Literal::new("Doe"),
        ["D".to_owned()],
        false,
    ));
    name.given_part(NamePartValue::new(
        Literal::new("John"),
        ["J".to_owned()],
        false,
    ));
    let name = name.freeze().expect("complete name");

    let mut entry = EntryBuilder::new(
        EntryId::new("F1").expect("valid entry"),
        EntryType::new("book").expect("valid type"),
        source(),
    );
    let values = [
        field("author", FieldValue::NameList(NameList::new([name], false))),
        field(
            "namehash",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field(
            "fullhash",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field(
            "fullhashraw",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field(
            "bibnamehash",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field(
            "authorbibnamehash",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field(
            "authornamehash",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field(
            "authorfullhash",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field(
            "authorfullhashraw",
            FieldValue::Literal(Literal::new("bd051a2f7a5f377e3a62581b0e0f8577")),
        ),
        field("labelalpha", FieldValue::Literal(Literal::new("\\emph{A}"))),
        field("sortinit", FieldValue::Literal(Literal::new("A"))),
        field(
            "sortinithash",
            FieldValue::Literal(Literal::new("2f401846e2029bad6b3ecc16d50031e2")),
        ),
        field("singletitle", FieldValue::Boolean(true)),
        field(
            "labelnamesource",
            FieldValue::Literal(Literal::new("author")),
        ),
        field(
            "labeltitlesource",
            FieldValue::Literal(Literal::new("title")),
        ),
        field("shorthand", FieldValue::Literal(Literal::new("\\emph{A}"))),
        field(
            "title",
            FieldValue::Literal(Literal::new("The Fullness of Times")),
        ),
        field("year", FieldValue::Integer(1995)),
    ];
    for value in values {
        entry
            .field(
                value.id().clone(),
                value.value().clone(),
                value.stage(),
                value.provenance().clone(),
            )
            .expect("field is unique");
    }
    let entry = entry.freeze();
    let id = entry.id().clone();
    let mut section = ProcessedSectionBuilder::new(SectionId::new(0));
    section.entry(entry).expect("unique entry");
    section
        .list(
            DataList::new(
                DataListId::new("custom/global//global/global/global").expect("valid list"),
                [id.clone()],
            )
            .expect("valid list"),
        )
        .expect("known entry");
    section
        .list(
            DataList::new(
                DataListId::new("shorthand/global//global/global/global").expect("valid list"),
                [id.clone()],
            )
            .expect("valid list")
            .with_kind(DataListKind::List),
        )
        .expect("known entry");
    let nty = DataList::new(
        DataListId::new("nty/global//global/global/global").expect("valid list"),
        [id.clone()],
    )
    .expect("valid list")
    .with_context_fields(
        &id,
        [
            field("sortinit", FieldValue::Literal(Literal::new("D"))),
            field(
                "sortinithash",
                FieldValue::Literal(Literal::new("6f385f66841fb5e82009dc833c761848")),
            ),
        ],
    )
    .expect("known contextual entry");
    section.list(nty).expect("known entry");
    section
        .alias(EntryId::new("F1a").expect("valid alias"), id)
        .expect("resolved alias");
    section
        .undefined_key(EntryId::new("C1").expect("valid key"))
        .expect("unique undefined key");

    let mut document = ProcessedBibliographyBuilder::new(
        BibConfigurationBuilder::new(COMPATIBILITY_VERSION).freeze(),
    );
    document.section(section.freeze()).expect("unique section");
    let actual = serialize(&document.freeze(), &request()).expect("serializes");
    assert_eq!(
        actual.bytes(),
        include_bytes!("../../../tests/corpus/bib/upstream-2.22/tdata/full-bbl.bbl")
    );
}

#[test]
fn serializes_typed_values_annotations_and_declared_order() {
    let mut entry = EntryBuilder::new(
        EntryId::new("typed").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    let values = [
        field("enabled", FieldValue::Boolean(false)),
        field("raw", FieldValue::Verbatim(Verbatim::new("a%b"))),
        field(
            "tags",
            FieldValue::LiteralList(vec![Literal::new("one"), Literal::new("two")]),
        ),
        field(
            "links",
            FieldValue::UriList(vec![Uri::new("https://example.test/a").expect("valid URI")]),
        ),
        field(
            "pages",
            FieldValue::RangeList(vec![Range::new(
                RangeEndpoint::Integer(1),
                RangeEndpoint::Integer(4),
            )]),
        ),
        field(
            "date",
            FieldValue::Date(
                DateValue::new(2026, Some(7), Some(17))
                    .expect("valid date")
                    .with_uncertain(true),
            ),
        ),
    ];
    for value in values {
        entry
            .field(
                value.id().clone(),
                value.value().clone(),
                value.stage(),
                value.provenance().clone(),
            )
            .expect("unique field");
    }
    entry
        .annotation(
            bib_model::Annotation::new(FieldId::new("note").expect("valid field"), "reviewed")
                .expect("valid annotation"),
        )
        .expect("unique annotation");
    let bytes = serialize(&document_with_entry(entry.freeze()), &request())
        .expect("serializes")
        .bytes()
        .to_vec();
    let text = String::from_utf8(bytes).expect("UTF-8 output");
    for expected in [
        "\\false{enabled}",
        "\\verb{raw}\n      \\verb a%b\n      \\endverb",
        "\\list{tags}{2}{%",
        "\\list{links}{1}{%",
        "\\range{pages}{1}{%",
        "\\field{date}{2026-07-17?}",
        "\\annotation{note}{reviewed}",
    ] {
        assert!(text.contains(expected), "missing `{expected}` in {text}");
    }
}

#[test]
fn applies_newline_encoding_and_output_limits_with_typed_diagnostics() {
    let mut entry = EntryBuilder::new(
        EntryId::new("encoding").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    entry
        .field(
            FieldId::new("title").expect("valid field"),
            FieldValue::Literal(Literal::new("Café")),
            FieldValueStage::Normalized,
            provenance(),
        )
        .expect("unique field");
    let document = document_with_entry(entry.freeze());
    let encoded = serialize(
        &document,
        &request()
            .with_encoding(LegacyEncoding::Latin1)
            .with_newline(OutputNewline::CrLf),
    )
    .expect("Latin-1 serializes");
    assert!(encoded.bytes().windows(2).any(|bytes| bytes == b"\r\n"));
    assert!(encoded.bytes().contains(&0xe9));

    let error = serialize(&document, &request().with_max_bytes(16)).expect_err("limit fails");
    assert_eq!(error.kind(), BblOutputFailureKind::Limit);
    assert_eq!(
        error
            .diagnostics()
            .next()
            .expect("diagnostic")
            .code()
            .as_str(),
        "BIB_OUTPUT_LIMIT"
    );

    let mut unrepresentable = EntryBuilder::new(
        EntryId::new("emoji").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    unrepresentable
        .field(
            FieldId::new("title").expect("valid field"),
            FieldValue::Literal(Literal::new("🦀")),
            FieldValueStage::Normalized,
            provenance(),
        )
        .expect("unique field");
    let error = serialize(
        &document_with_entry(unrepresentable.freeze()),
        &request().with_encoding(LegacyEncoding::Latin1),
    )
    .expect_err("unrepresentable value fails");
    assert_eq!(error.kind(), BblOutputFailureKind::Unrepresentable);
}

#[test]
fn full_bibtex_fixture_is_byte_exact() {
    let mut space = EntryBuilder::new(
        EntryId::new("westfahl:space").expect("valid entry"),
        EntryType::new("incollection").expect("valid type"),
        source(),
    );
    add_field(
        &mut space,
        "author",
        FieldValue::NameList(NameList::new([person("Westfahl", "Gary")], false)),
    );
    add_literal(
        &mut space,
        "annotation",
        "A cross-referenced article from a \\texttt{collection}. This is an \\texttt{incollection} entry with a \\texttt{crossref} field. Note the \\texttt{subtitle} and \\texttt{indextitle} fields",
    );
    add_literal(&mut space, "crossref", "westfahl:frontier");
    add_literal(&mut space, "indextitle", "True Frontier, The");
    add_literal(&mut space, "langid", "english");
    add_literal(&mut space, "langidopts", "variant=american");
    add_field(
        &mut space,
        "pages",
        FieldValue::RangeList(vec![Range::new(
            RangeEndpoint::Integer(55),
            RangeEndpoint::Integer(65),
        )]),
    );
    add_literal(
        &mut space,
        "subtitle",
        "Confronting and Avoiding the Realities of Space in American Science Fiction Films",
    );
    add_literal(&mut space, "title", "The True Frontier");

    let mut article = EntryBuilder::new(
        EntryId::new("kastenholz").expect("valid entry"),
        EntryType::new("article").expect("valid type"),
        source(),
    );
    add_literal(
        &mut article,
        "abstract",
        "The computation of ionic solvation free energies from atomistic simulations is a surprisingly difficult problem that has found no satisfactory solution for more than 15 years. The reason is that the charging free energies evaluated from such simulations are affected by very large errors. One of these is related to the choice of a specific convention for summing up the contributions of solvent charges to the electrostatic potential in the ionic cavity, namely, on the basis of point charges within entire solvent molecules (M scheme) or on the basis of individual point charges (P scheme). The use of an inappropriate convention may lead to a charge-independent offset in the calculated potential, which depends on the details of the summation scheme, on the quadrupole-moment trace of the solvent molecule, and on the approximate form used to represent electrostatic interactions in the system. However, whether the M or P scheme (if any) represents the appropriate convention is still a matter of on-going debate. The goal of the present article is to settle this long-standing controversy by carefully analyzing (both analytically and numerically) the properties of the electrostatic potential in molecular liquids (and inside cavities within them).",
    );
    add_field(
        &mut article,
        "author",
        FieldValue::NameList(NameList::new(
            [
                person("Kastenholz", "M. A."),
                person("Hünenberger", "Philippe H."),
            ],
            false,
        )),
    );
    add_literal(
        &mut article,
        "annotation",
        "An \\texttt{article} entry with an \\texttt{eid} and a \\texttt{doi} field. Note that the \\textsc{doi} is transformed into a clickable link if \\texttt{hyperref} support has been enabled",
    );
    add_field(
        &mut article,
        "date",
        FieldValue::Date(DateValue::new(2006, None, None).expect("valid date")),
    );
    add_literal(&mut article, "doi", "10.1063/1.2172593");
    add_field(&mut article, "eid", FieldValue::Integer(124106));
    add_literal(
        &mut article,
        "indextitle",
        "Computation of ionic solvation free energies",
    );
    add_literal(&mut article, "journaltitle", "J.~Chem. Phys.");
    add_literal(&mut article, "langid", "english");
    add_literal(&mut article, "langidopts", "variant=american");
    add_literal(
        &mut article,
        "subtitle",
        "I. The electrostatic potential in molecular liquids",
    );
    add_literal(
        &mut article,
        "title",
        "Computation of methodology\\hyphen independent ionic solvation free energies from molecular simulations",
    );
    add_field(&mut article, "volume", FieldValue::Integer(124));

    let mut collection = EntryBuilder::new(
        EntryId::new("westfahl:frontier").expect("valid entry"),
        EntryType::new("collection").expect("valid type"),
        source(),
    );
    add_field(
        &mut collection,
        "editor",
        FieldValue::NameList(NameList::new([person("Westfahl", "Gary")], false)),
    );
    add_field(
        &mut collection,
        "location",
        FieldValue::LiteralList(vec![
            Literal::new("Westport, Conn."),
            Literal::new("London"),
        ]),
    );
    add_literal(&mut collection, "publisher", "Greenwood");
    add_literal(
        &mut collection,
        "annotation",
        "This is a \\texttt{collection} entry. Note the format of the \\texttt{location} field as well as the \\texttt{subtitle} and \\texttt{booksubtitle} fields",
    );
    add_literal(
        &mut collection,
        "booksubtitle",
        "The Frontier Theme in Science Fiction",
    );
    add_literal(&mut collection, "booktitle", "Space and Beyond");
    add_field(
        &mut collection,
        "date",
        FieldValue::Date(DateValue::new(2000, None, None).expect("valid date")),
    );
    add_literal(&mut collection, "langid", "english");
    add_literal(&mut collection, "langidopts", "variant=american");
    add_literal(
        &mut collection,
        "subtitle",
        "The Frontier Theme in Science Fiction",
    );
    add_literal(&mut collection, "title", "Space and Beyond");

    let entries = [space.freeze(), article.freeze(), collection.freeze()];
    let ids = entries
        .iter()
        .map(|entry| entry.id().clone())
        .collect::<Vec<_>>();
    let mut section = ProcessedSectionBuilder::new(SectionId::new(0));
    for entry in entries {
        section.entry(entry).expect("unique entry");
    }
    section
        .list(
            DataList::new(
                DataListId::new("nty/global//global/global/global").expect("valid list"),
                ids,
            )
            .expect("valid list"),
        )
        .expect("known entries");
    let mut document = ProcessedBibliographyBuilder::new(
        BibConfigurationBuilder::new(COMPATIBILITY_VERSION).freeze(),
    );
    document.section(section.freeze()).expect("unique section");
    let serializer =
        BibtexSerializer::new(BibtexOptions::default().with_alignment(true).with_macros([
            BibtexMacro::new("JCHPH", "J.~Chem. Phys.").with_fields(["journaltitle"]),
        ]));
    let actual = serializer
        .serialize(
            OutputContext::new(&document.freeze(), &UnicodeData::pinned()),
            &bibtex_request(),
        )
        .expect("serializes");
    assert_eq!(
        actual.bytes(),
        include_bytes!("../../../tests/corpus/bib/upstream-2.22/tdata/full-bibtex_biber.bib")
    );
}

#[test]
fn bibtex_renders_typed_fields_comments_options_and_failures() {
    let mut entry = EntryBuilder::new(
        EntryId::new("typed").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    add_field(&mut entry, "enabled", FieldValue::Boolean(true));
    add_field(
        &mut entry,
        "keys",
        FieldValue::KeyList(vec![
            EntryId::new("a").expect("valid key"),
            EntryId::new("b").expect("valid key"),
        ]),
    );
    add_field(
        &mut entry,
        "names",
        FieldValue::NameList(NameList::new([person("Doe", "Jane")], true)),
    );
    add_literal(&mut entry, "symbol", "α");
    entry
        .annotation(
            bib_model::Annotation::for_field(
                FieldId::new("names").expect("valid annotation target"),
                FieldId::new("default").expect("valid annotation name"),
                "1=primary",
            )
            .expect("valid annotation"),
        )
        .expect("unique annotation");
    let document = document_with_entry(entry.freeze());
    let serializer = BibtexSerializer::new(
        BibtexOptions::default()
            .with_comments(["generated deterministically"])
            .with_field_case(crate::BibtexCase::Lower)
            .with_escape(bib_unicode::RecodeSet::Full),
    );
    let output = serializer
        .serialize(
            OutputContext::new(&document, &UnicodeData::pinned()),
            &bibtex_request().with_newline(OutputNewline::CrLf),
        )
        .expect("serializes");
    let text = String::from_utf8(output.bytes().to_vec()).expect("UTF-8");
    assert!(text.starts_with("% generated deterministically\r\n\r\n@MISC{typed,"));
    assert!(text.contains("  enabled = {true},\r\n"));
    assert!(text.contains("  keys = {a,b},\r\n"));
    assert!(text.contains("  names = {Doe, Jane and others},\r\n"));
    assert!(text.contains("  names+an:default = {1=primary},\r\n"));
    assert!(text.contains("  symbol = {{$\\alpha$}},\r\n"));

    let error = serializer
        .serialize(
            OutputContext::new(&document, &UnicodeData::pinned()),
            &bibtex_request().with_max_bytes(8),
        )
        .expect_err("limit fails");
    assert_eq!(error.kind(), BibtexOutputFailureKind::Limit);

    let mut emoji = EntryBuilder::new(
        EntryId::new("emoji").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    add_literal(&mut emoji, "title", "🦀");
    let error = BibtexSerializer::default()
        .serialize(
            OutputContext::new(&document_with_entry(emoji.freeze()), &UnicodeData::pinned()),
            &bibtex_request().with_encoding(LegacyEncoding::Latin1),
        )
        .expect_err("encoding fails");
    assert_eq!(error.kind(), BibtexOutputFailureKind::Unrepresentable);

    let mut malformed = EntryBuilder::new(
        EntryId::new("malformed").expect("valid entry"),
        EntryType::new("misc").expect("valid type"),
        source(),
    );
    add_literal(&mut malformed, "title", "unbalanced {");
    let error = BibtexSerializer::default()
        .serialize(
            OutputContext::new(
                &document_with_entry(malformed.freeze()),
                &UnicodeData::pinned(),
            ),
            &bibtex_request(),
        )
        .expect_err("malformed value fails");
    assert_eq!(error.kind(), BibtexOutputFailureKind::MalformedValue);
}

#[test]
fn bibtex_output_entries_match_upstream_exactly() {
    let serializer = BibtexSerializer::new(BibtexOptions::default().with_alignment(true));
    let mut murray = EntryBuilder::new(
        EntryId::new("murray").expect("valid entry"),
        EntryType::new("article").expect("valid type"),
        source(),
    );
    let authors = [
        ("Hostetler", "Michael J."),
        ("Wingate", "Julia E."),
        ("Zhong", "Chuan-Jian"),
        ("Harris", "Jay E."),
        ("Vachet", "Richard W."),
        ("Clark", "Michael R."),
        ("Londono", "J. David"),
        ("Green", "Stephen J."),
        ("Stokes", "Jennifer J."),
        ("Wignall", "George D."),
        ("Glish", "Gary L."),
        ("Porter", "Marc D."),
        ("Evans", "Neal D."),
        ("Murray", "Royce W."),
    ]
    .map(|(family, given)| person(family, given));
    add_field(
        &mut murray,
        "author",
        FieldValue::NameList(NameList::new(authors, false)),
    );
    add_literal(
        &mut murray,
        "annotation",
        "An \\texttt{article} entry with \\arabic{author} authors. By default, long author and editor lists are automatically truncated. This is configurable",
    );
    add_field(
        &mut murray,
        "date",
        FieldValue::Date(DateValue::new(1998, None, None).expect("valid date")),
    );
    add_literal(
        &mut murray,
        "indextitle",
        "Alkanethiolate gold cluster molecules",
    );
    add_literal(&mut murray, "journaltitle", "Langmuir");
    add_literal(&mut murray, "langid", "english");
    add_literal(&mut murray, "langidopts", "variant=american");
    add_field(&mut murray, "number", FieldValue::Integer(1));
    add_field(
        &mut murray,
        "pages",
        FieldValue::RangeList(vec![Range::new(
            RangeEndpoint::Integer(17),
            RangeEndpoint::Integer(30),
        )]),
    );
    add_literal(
        &mut murray,
        "shorttitle",
        "Alkanethiolate gold cluster molecules",
    );
    add_literal(
        &mut murray,
        "subtitle",
        "Core and monolayer properties as a function of core size",
    );
    add_literal(
        &mut murray,
        "title",
        "Alkanethiolate gold cluster molecules with core diameters from 1.5 to 5.2~nm",
    );
    add_field(&mut murray, "volume", FieldValue::Integer(14));
    assert_eq!(
        serializer.serialize_entry(&murray.freeze()).expect("entry"),
        "@ARTICLE{murray,\n  AUTHOR       = {Hostetler, Michael J. and Wingate, Julia E. and Zhong, Chuan-Jian and Harris, Jay E. and Vachet, Richard W. and Clark, Michael R. and Londono, J. David and Green, Stephen J. and Stokes, Jennifer J. and Wignall, George D. and Glish, Gary L. and Porter, Marc D. and Evans, Neal D. and Murray, Royce W.},\n  ANNOTATION   = {An \\texttt{article} entry with \\arabic{author} authors. By default, long author and editor lists are automatically truncated. This is configurable},\n  DATE         = {1998},\n  INDEXTITLE   = {Alkanethiolate gold cluster molecules},\n  JOURNALTITLE = {Langmuir},\n  LANGID       = {english},\n  LANGIDOPTS   = {variant=american},\n  NUMBER       = {1},\n  PAGES        = {17--30},\n  SHORTTITLE   = {Alkanethiolate gold cluster molecules},\n  SUBTITLE     = {Core and monolayer properties as a function of core size},\n  TITLE        = {Alkanethiolate gold cluster molecules with core diameters from 1.5 to 5.2~nm},\n  VOLUME       = {14},\n}\n\n"
    );

    let mut book = EntryBuilder::new(
        EntryId::new("b1").expect("valid entry"),
        EntryType::new("book").expect("valid type"),
        source(),
    );
    add_field(
        &mut book,
        "location",
        FieldValue::LiteralList(vec![Literal::new("London"), Literal::new("Edinburgh")]),
    );
    book.annotation(
        bib_model::Annotation::for_field(
            FieldId::new("location").expect("valid target"),
            FieldId::new("default").expect("valid annotation"),
            "1=ann1;2=ann2",
        )
        .expect("valid annotation"),
    )
    .expect("unique annotation");
    add_field(
        &mut book,
        "date",
        FieldValue::Date(DateValue::new(1999, None, None).expect("valid date")),
    );
    add_literal(&mut book, "mainsubtitle", "Mainsubtitle");
    add_literal(&mut book, "maintitle", "Maintitle");
    add_literal(&mut book, "maintitleaddon", "Maintitleaddon");
    add_literal(&mut book, "title", "Booktitle");
    book.annotation(
        bib_model::Annotation::for_field(
            FieldId::new("title").expect("valid target"),
            FieldId::new("default").expect("valid annotation"),
            "=ann1, ann2",
        )
        .expect("valid annotation"),
    )
    .expect("unique annotation");
    assert_eq!(
        serializer.serialize_entry(&book.freeze()).expect("entry"),
        "@BOOK{b1,\n  LOCATION            = {London and Edinburgh},\n  LOCATION+an:default = {1=ann1;2=ann2},\n  DATE                = {1999},\n  MAINSUBTITLE        = {Mainsubtitle},\n  MAINTITLE           = {Maintitle},\n  MAINTITLEADDON      = {Maintitleaddon},\n  TITLE               = {Booktitle},\n  TITLE+an:default    = {=ann1, ann2},\n}\n\n"
    );

    let mut ids = EntryBuilder::new(
        EntryId::new("bo1").expect("valid entry"),
        EntryType::new("book").expect("valid type"),
        source(),
    );
    add_field(
        &mut ids,
        "author",
        FieldValue::NameList(NameList::new([person("Smith", "Simon")], false)),
    );
    add_field(
        &mut ids,
        "ids",
        FieldValue::KeyList(vec![
            EntryId::new("box1").expect("valid key"),
            EntryId::new("box2").expect("valid key"),
        ]),
    );
    assert_eq!(
        serializer.serialize_entry(&ids.freeze()).expect("entry"),
        "@BOOK{bo1,\n  AUTHOR = {Smith, Simon},\n  IDS    = {box1,box2},\n}\n\n"
    );
}
