use crate::{EngineMode, ResourceRequest};

use super::*;

const PRIMITIVE_GENERATED: &[u8] =
    include_bytes!("../../../../tests/corpus/stabilization/primitive-generated.tex");

fn options() -> EditorSessionOptions {
    EditorSessionOptions {
        tex: SessionOptions {
            engine: EngineMode::Tex82,
            ..SessionOptions::default()
        },
        stabilization: FixedPointLimits::default(),
    }
}

fn finish_advance(session: &mut EditorCompileSession) -> MemoryRunOutput {
    loop {
        match session.advance() {
            CompileAttemptResult::Complete(output) => return output,
            CompileAttemptResult::Error(error) => panic!("editor pass failed: {error}"),
            CompileAttemptResult::NeedResources(needs) => {
                let responses = needs
                    .required
                    .into_iter()
                    .chain(needs.probes)
                    .map(|request| match request {
                        ResourceRequest::File(request) => {
                            ResourceResponse::FileUnavailable(request.key().clone())
                        }
                        request => panic!("unexpected non-file resource: {request:?}"),
                    })
                    .collect();
                session.provide_resources(responses).expect("resources");
            }
        }
    }
}

#[test]
fn no_op_stabilization_skips_reruns_but_changed_unused_output_is_selected() {
    let mut session = EditorCompileSession::new(options()).expect("session");
    session
        .add_user_file("/job/main.tex", PRIMITIVE_GENERATED.to_vec())
        .expect("source");
    finish_advance(&mut session);
    let initial = match session.stabilize_attempt() {
        EditorStabilizationAttempt::Complete(output) => output,
        other => panic!("initial stabilization failed: {other:?}"),
    };
    assert_eq!(initial.passes, 2);

    let mut neutral = b"% neutral edit\n".to_vec();
    neutral.extend_from_slice(PRIMITIVE_GENERATED);
    session
        .apply_patch(SourcePatch {
            base_revision: initial.revision,
            next_revision: tex_incr::RevisionId::new(2),
            expected_hash: initial.content_hash,
            range: 0..PRIMITIVE_GENERATED.len(),
            replacement: String::from_utf8(neutral.clone()).expect("ASCII fixture"),
        })
        .expect("neutral patch");
    finish_advance(&mut session);
    assert!(matches!(
        session.status(),
        Some(EditorSessionStatus::Stable {
            revision,
            passes: 1,
            stabilization_required: false,
        }) if revision == tex_incr::RevisionId::new(2)
    ));
    let no_op = match session.stabilize_attempt() {
        EditorStabilizationAttempt::Complete(output) => output,
        other => panic!("no-op stabilization failed: {other:?}"),
    };
    assert_eq!(
        no_op.passes, 1,
        "stable generated bytes require no cold rerun"
    );

    let unused = neutral
        .windows(b"unused-v1".len())
        .position(|window| window == b"unused-v1")
        .expect("unused output marker");
    let mut changed_unused = neutral.clone();
    changed_unused.splice(
        unused..unused + b"unused-v1".len(),
        b"unused-v2".iter().copied(),
    );
    session
        .apply_patch(SourcePatch {
            base_revision: no_op.revision,
            next_revision: tex_incr::RevisionId::new(3),
            expected_hash: no_op.content_hash,
            range: 0..neutral.len(),
            replacement: String::from_utf8(changed_unused).expect("ASCII fixture"),
        })
        .expect("unused-output patch");
    finish_advance(&mut session);
    assert!(matches!(
        session.status(),
        Some(EditorSessionStatus::Provisional {
            stabilization_required: true,
            ..
        })
    ));
    let stabilized = match session.stabilize_attempt() {
        EditorStabilizationAttempt::Complete(output) => output,
        other => panic!("unused-output stabilization failed: {other:?}"),
    };
    assert_eq!(stabilized.passes, 2);
    assert_eq!(
        stabilized
            .generated_files
            .iter()
            .find(|file| file.path == std::path::Path::new("/job/unused.aux"))
            .expect("selected unused output")
            .bytes,
        b"unused-v2\n"
    );
}

#[test]
fn one_pass_is_provisional_and_stabilization_keeps_revision() {
    let source = br#"\openin0=state.aux
\ifeof0 \def\value{first}\else \read0 to \value \closein0 \fi
\immediate\openout1=state.aux
\immediate\write1{stable}
\immediate\closeout1
\shipout\hbox{\value}\end
"#;
    let mut session = EditorCompileSession::new(options()).expect("session");
    session
        .add_user_file("/job/main.tex", source.to_vec())
        .expect("source");
    let CompileAttemptResult::NeedResources(needs) = session.advance() else {
        panic!("initial generated-input probe");
    };
    let [ResourceRequest::File(probe)] = needs.probes.as_slice() else {
        panic!("one probe");
    };
    session
        .provide_resources(vec![ResourceResponse::FileUnavailable(probe.key().clone())])
        .expect("negative probe");
    assert!(matches!(
        session.advance(),
        CompileAttemptResult::Complete(_)
    ));
    assert_eq!(
        session.status(),
        Some(EditorSessionStatus::Provisional {
            revision: tex_incr::RevisionId::new(1),
            stabilization_required: true,
        })
    );
    assert!(session.stable_output().is_none());

    let completed = match session.stabilize_attempt() {
        EditorStabilizationAttempt::Complete(output) => output,
        other => panic!("stable output, got {other:?}"),
    };
    assert_eq!(completed.revision, tex_incr::RevisionId::new(1));
    assert_eq!(completed.passes, 2);
    assert_eq!(session.display_output(), Some(completed.as_ref()));
    assert_eq!(session.stable_output(), Some(completed.as_ref()));
    assert_eq!(
        session.status(),
        Some(EditorSessionStatus::Stable {
            revision: tex_incr::RevisionId::new(1),
            passes: 2,
            stabilization_required: false,
        })
    );

    session
        .apply_patch(SourcePatch {
            base_revision: tex_incr::RevisionId::new(1),
            next_revision: tex_incr::RevisionId::new(2),
            expected_hash: completed.content_hash,
            range: 0..source.len(),
            replacement: "\\end\n".into(),
        })
        .expect("the next public revision follows the root edit, not internal passes");
    assert!(matches!(
        session.advance(),
        CompileAttemptResult::Complete(_)
    ));
    assert!(matches!(
        session.status(),
        Some(EditorSessionStatus::Provisional {
            revision,
            stabilization_required: true,
        }) if revision == tex_incr::RevisionId::new(2)
    ));
}

#[test]
fn failed_stabilization_preserves_display_and_prior_stable_output() {
    let original = br"\shipout\hbox{old}\end
"
    .to_vec();
    let mut session = EditorCompileSession::new(options()).expect("session");
    session
        .add_user_file("/job/main.tex", original.clone())
        .expect("source");
    assert!(matches!(
        session.advance(),
        CompileAttemptResult::Complete(_)
    ));
    let stable_revision_one = session.stable_output().expect("initial stable").clone();

    let edited = r#"\openin0=state.aux
\ifeof0 \else \closein0 \input state.aux \fi
\immediate\openout1=state.aux
\immediate\write1{\noexpand\input remote}
\immediate\closeout1
\shipout\hbox{new}\end
"#;
    session
        .apply_patch(SourcePatch {
            base_revision: tex_incr::RevisionId::new(1),
            next_revision: tex_incr::RevisionId::new(2),
            expected_hash: ContentHash::from_bytes(&original),
            range: 0..original.len(),
            replacement: edited.into(),
        })
        .expect("patch");
    let CompileAttemptResult::NeedResources(needs) = session.advance() else {
        panic!("missing state probe");
    };
    let [ResourceRequest::File(probe)] = needs.probes.as_slice() else {
        panic!("one state probe");
    };
    session
        .provide_resources(vec![ResourceResponse::FileUnavailable(probe.key().clone())])
        .expect("negative state probe");
    assert!(matches!(
        session.advance(),
        CompileAttemptResult::Complete(_)
    ));
    let provisional = session.display_output().expect("provisional").clone();

    let attempt = session.stabilize_attempt();
    let EditorStabilizationAttempt::NeedResources(needs) = attempt else {
        panic!("second pass requests remote input, got {attempt:?}");
    };
    assert_eq!(
        session.status(),
        Some(EditorSessionStatus::Stabilizing {
            revision: tex_incr::RevisionId::new(2),
            completed_passes: 1,
            stabilization_required: true,
        })
    );
    let [ResourceRequest::File(request)] = needs.required.as_slice() else {
        panic!("one remote request");
    };
    let request = request.clone();
    assert!(session.cancel_stabilization());
    assert_eq!(session.display_output(), Some(&provisional));
    assert_eq!(session.stable_output(), Some(&stable_revision_one));
    let EditorStabilizationAttempt::NeedResources(needs) = session.stabilize_attempt() else {
        panic!("cancelled stabilization should restart and request remote input");
    };
    let [ResourceRequest::File(restarted)] = needs.required.as_slice() else {
        panic!("one restarted remote request");
    };
    assert_eq!(restarted.key(), request.key());
    session
        .provide_resources(vec![ResourceResponse::FileUnavailable(
            restarted.key().clone(),
        )])
        .expect("negative remote response");
    assert!(matches!(
        session.stabilize_attempt(),
        EditorStabilizationAttempt::Error(TexFixedPointError::Compile(_))
    ));
    assert_eq!(session.display_output(), Some(&provisional));
    assert_eq!(session.stable_output(), Some(&stable_revision_one));
    assert!(matches!(
        session.status(),
        Some(EditorSessionStatus::Provisional {
            revision,
            stabilization_required: true,
        }) if revision == tex_incr::RevisionId::new(2)
    ));
}
