[package]
name = "tex-incr"
version.workspace = true
edition.workspace = true

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
tex-command = { path = "../tex-command" }
tex-exec = { path = "../tex-exec" }
tex-fonts = { path = "../tex-fonts" }
tex-out = { path = "../tex-out" }
tex-state = { path = "../tex-state" }

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true
tex-state = { path = "../tex-state", features = ["testing"] }

[lints]
workspace = true
