//! Generated-on-demand full-document TeX82 trace registry.
//!
//! The committed registry under `tests/corpus/command/tex82` holds small,
//! focused fixtures whose complete oracle streams are cheap to version. Full
//! documents are not: one plain-bootstrap trace is roughly 17 MB and Gentle's
//! is roughly 156 MB, so committing raw document traces would add hundreds of
//! megabytes of generated bytes to the repository for artifacts that are
//! exactly reproducible from the pinned oracle.
//!
//! This tier therefore keeps the same `tex-oracle` fixture discipline --
//! `bootstrap_tex82_fixture` derives a real, fully validated fixture directory
//! with a manifest-bound stream -- but the fixture tree itself is gitignored
//! and regenerated by `scripts/build-tex82-document-traces.sh`. Identity is
//! preserved by pinning each document's fixture-manifest digest, event count,
//! and staged font-set digest in the committed
//! [`DOCUMENT_CONTRACT`]; the manifest in turn pins every source, output, and
//! event byte, so a drifted regeneration fails loudly instead of silently
//! becoming the new expectation.
//!
//! Documents whose trace tree is absent are reported as skipped rather than
//! failing: the committed suite stays hermetic and this tier is opt-in on the
//! generated artifacts being present.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};
use tex_oracle::CommittedFixture;

use crate::{ReplayResources, RunnerError};

/// Committed pin file binding each generated document trace to its exact
/// oracle identity.
pub const DOCUMENT_CONTRACT: &str = "tests/tex82-document-trace-manifest.txt";
/// Gitignored root the generation script publishes validated document
/// fixtures into.
pub const DOCUMENT_FIXTURE_ROOT: &str = "tests/corpus/command/tex82-documents";
/// Subdirectory of a generated document fixture holding the exact TFM bytes
/// the oracle run resolved, so canonical replay registers identical metrics.
const DOCUMENT_FONT_DIRECTORY: &str = "fonts";
const DOCUMENT_CONTRACT_SCHEMA: u32 = 1;

/// One registered document, resolved against the generated trace tree.
pub struct DocumentTrace {
    /// Stable document selector (`plain`, `story`, `gentle`).
    pub name: String,
    pub directory: PathBuf,
    pub fixture: CommittedFixture,
    pub resources: ReplayResources,
}

/// A validated registry row whose large event stream is loaded only when its
/// turn is replayed. Keeping all three parsed document streams alive made the
/// exhaustive diagnostic retain Plain and Story while Gentle alone needed
/// most of the 512 MiB contract.
pub struct DocumentTraceEntry {
    directory: PathBuf,
    record: DocumentRecord,
}

impl DocumentTraceEntry {
    pub fn load(self) -> Result<DocumentTrace, RunnerError> {
        load_trace(&self.directory, self.record)
    }
}

/// The registry as it exists on this checkout: present documents in contract
/// order, plus the names of registered documents whose generated tree is
/// absent.
pub struct DocumentRegistry {
    pub traces: Vec<DocumentTraceEntry>,
    pub skipped: Vec<String>,
}

#[derive(Debug)]
struct DocumentRecord {
    name: String,
    root_source: String,
    manifest_sha256: String,
    events: usize,
    fonts_sha256: String,
}

/// Loads every registered document trace whose generated fixture tree is
/// present, verifying its pinned identity first.
///
/// A missing *trace tree* is not an error: this tier is generated on demand,
/// and the caller reports each absent document as an uncompared fixture. A
/// missing *contract file* is an error: the contract is committed, so its
/// absence means the checkout cannot say what it was supposed to compare, and
/// an empty registry read as "no documents are registered" is exactly the
/// silent under-report the pin exists to prevent. A present tree whose
/// identity disagrees with the contract is likewise an error.
pub fn load_registry(repository: &Path) -> Result<DocumentRegistry, RunnerError> {
    let contract_path = repository.join(DOCUMENT_CONTRACT);
    if !contract_path.is_file() {
        return Err(RunnerError::Document(format!(
            "{DOCUMENT_CONTRACT} is absent; it is committed, so this checkout cannot say which \
             document traces are registered"
        )));
    }
    let records = parse_contract(&read(&contract_path)?)?;
    let mut traces = Vec::new();
    let mut skipped = Vec::new();
    for record in records {
        let directory = repository.join(DOCUMENT_FIXTURE_ROOT).join(&record.name);
        if !directory.join("manifest.json").is_file() {
            skipped.push(record.name);
            continue;
        }
        // Manifest/event identity is checked when this entry is loaded. Do
        // not parse every full-document stream up front: each predecessor is
        // dropped before the next document enters memory.
        traces.push(DocumentTraceEntry { directory, record });
    }
    Ok(DocumentRegistry { traces, skipped })
}

fn load_trace(directory: &Path, record: DocumentRecord) -> Result<DocumentTrace, RunnerError> {
    let manifest = read(&directory.join("manifest.json"))?;
    if sha256(&manifest) != record.manifest_sha256 {
        return Err(RunnerError::Document(format!(
            "{} fixture manifest identity drifted from {DOCUMENT_CONTRACT}; regenerate with scripts/build-tex82-document-traces.sh",
            record.name
        )));
    }
    let fixture = CommittedFixture::load(directory)
        .map_err(|error| RunnerError::Document(format!("{} is invalid: {error}", record.name)))?;
    if fixture.stream.events.len() != record.events {
        return Err(RunnerError::Document(format!(
            "{} committed {} events; {DOCUMENT_CONTRACT} pins {}",
            record.name,
            fixture.stream.events.len(),
            record.events
        )));
    }
    if fixture.manifest.root_source != record.root_source {
        return Err(RunnerError::Document(format!(
            "{} fixture root source {} disagrees with {DOCUMENT_CONTRACT} root source {}",
            record.name, fixture.manifest.root_source, record.root_source
        )));
    }
    let fonts = load_fonts(directory)?;
    if font_set_identity(&fonts) != record.fonts_sha256 {
        return Err(RunnerError::Document(format!(
            "{} staged font set drifted from {DOCUMENT_CONTRACT}; regenerate with scripts/build-tex82-document-traces.sh",
            record.name
        )));
    }
    Ok(DocumentTrace {
        name: record.name,
        directory: directory.to_path_buf(),
        fixture,
        resources: ReplayResources { fonts },
    })
}

/// Reads the TFM bytes the oracle run resolved. Fonts are staged beside the
/// fixture rather than declared as fixture sources because fixture contract 1
/// models `sources` as focused `.tex` inputs whose event locations are
/// validated; a TFM is an opaque metric resource with no source locations.
fn load_fonts(directory: &Path) -> Result<BTreeMap<String, Vec<u8>>, RunnerError> {
    let font_directory = directory.join(DOCUMENT_FONT_DIRECTORY);
    let mut fonts = BTreeMap::new();
    if !font_directory.is_dir() {
        return Ok(fonts);
    }
    let entries = read_directory(&font_directory)?;
    for entry in entries {
        let name = entry.file_name().to_string_lossy().into_owned();
        if !name.ends_with(".tfm") {
            continue;
        }
        fonts.insert(name, read(&entry.path())?);
    }
    Ok(fonts)
}

/// Deterministic aggregate identity over the staged font set: one
/// `name sha256` line per font in bytewise name order.
fn font_set_identity(fonts: &BTreeMap<String, Vec<u8>>) -> String {
    let mut preimage = String::new();
    for (name, bytes) in fonts {
        preimage.push_str(name);
        preimage.push(' ');
        preimage.push_str(&sha256(bytes));
        preimage.push('\n');
    }
    sha256(preimage.as_bytes())
}

fn parse_contract(contract: &[u8]) -> Result<Vec<DocumentRecord>, RunnerError> {
    let contract = std::str::from_utf8(contract)
        .map_err(|_| RunnerError::Document(format!("{DOCUMENT_CONTRACT} is not UTF-8")))?;
    let mut schema = None;
    let mut records: Vec<DocumentRecord> = Vec::new();
    for (index, line) in contract.lines().enumerate() {
        let number = index + 1;
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields = line.split_ascii_whitespace().collect::<Vec<_>>();
        match fields.as_slice() {
            ["contract-schema", version] => {
                schema = Some(version.parse::<u32>().map_err(|_| {
                    RunnerError::Document(format!(
                        "{DOCUMENT_CONTRACT} line {number} has a malformed contract schema"
                    ))
                })?);
            }
            [
                "document",
                name,
                root_source,
                manifest_sha256,
                events,
                fonts_sha256,
            ] => {
                let name = checked_name(name, number)?;
                if records.iter().any(|record| record.name == name) {
                    return Err(RunnerError::Document(format!(
                        "{DOCUMENT_CONTRACT} repeats document {name}"
                    )));
                }
                records.push(DocumentRecord {
                    name,
                    root_source: checked_name(root_source, number)?,
                    manifest_sha256: (*manifest_sha256).into(),
                    events: events.parse::<usize>().map_err(|_| {
                        RunnerError::Document(format!(
                            "{DOCUMENT_CONTRACT} line {number} has a malformed event count"
                        ))
                    })?,
                    fonts_sha256: (*fonts_sha256).into(),
                });
            }
            _ => {
                return Err(RunnerError::Document(format!(
                    "{DOCUMENT_CONTRACT} line {number} is malformed"
                )));
            }
        }
    }
    if schema != Some(DOCUMENT_CONTRACT_SCHEMA) {
        return Err(RunnerError::Document(format!(
            "{DOCUMENT_CONTRACT} does not declare contract-schema {DOCUMENT_CONTRACT_SCHEMA}"
        )));
    }
    Ok(records)
}

fn checked_name(name: &str, line: usize) -> Result<String, RunnerError> {
    if name.is_empty()
        || name.contains('/')
        || name.contains('\\')
        || name.contains('\0')
        || name == "."
        || name == ".."
    {
        return Err(RunnerError::Document(format!(
            "{DOCUMENT_CONTRACT} line {line} names unsafe path component {name:?}"
        )));
    }
    Ok(name.into())
}

#[allow(
    clippy::disallowed_methods,
    reason = "this offline host tool reads generated fixture bytes, not engine state"
)]
fn read(path: &Path) -> Result<Vec<u8>, RunnerError> {
    std::fs::read(path).map_err(|error| {
        RunnerError::Document(format!("failed to read {}: {error}", path.display()))
    })
}

#[allow(
    clippy::disallowed_methods,
    reason = "this offline host tool reads generated fixture bytes, not engine state"
)]
fn read_directory(directory: &Path) -> Result<Vec<std::fs::DirEntry>, RunnerError> {
    let mut entries = std::fs::read_dir(directory)
        .map_err(|error| {
            RunnerError::Document(format!("failed to read {}: {error}", directory.display()))
        })?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| {
            RunnerError::Document(format!("failed to read {}: {error}", directory.display()))
        })?;
    entries.sort_by_key(std::fs::DirEntry::file_name);
    Ok(entries)
}

fn sha256(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{DOCUMENT_CONTRACT_SCHEMA, font_set_identity, parse_contract};
    use std::collections::BTreeMap;

    #[test]
    fn contract_requires_its_schema_and_rejects_unsafe_names() {
        let record = parse_contract(b"contract-schema 1\ndocument plain root.tex aa 12 bb\n")
            .expect("valid contract");
        assert_eq!(record.len(), 1);
        assert_eq!(record[0].name, "plain");
        assert_eq!(record[0].events, 12);

        let error =
            parse_contract(b"document plain root.tex aa 12 bb\n").expect_err("schema is required");
        assert!(
            error
                .to_string()
                .contains(&format!("contract-schema {DOCUMENT_CONTRACT_SCHEMA}"))
        );

        let error = parse_contract(b"contract-schema 1\ndocument ../escape root.tex aa 1 bb\n")
            .expect_err("unsafe name is rejected");
        assert!(error.to_string().contains("unsafe path component"));
    }

    #[test]
    fn font_set_identity_is_order_independent_and_content_sensitive() {
        let mut first = BTreeMap::new();
        first.insert("b.tfm".to_owned(), b"second".to_vec());
        first.insert("a.tfm".to_owned(), b"first".to_vec());
        let mut second = BTreeMap::new();
        second.insert("a.tfm".to_owned(), b"first".to_vec());
        second.insert("b.tfm".to_owned(), b"second".to_vec());
        assert_eq!(font_set_identity(&first), font_set_identity(&second));

        second.insert("b.tfm".to_owned(), b"changed".to_vec());
        assert_ne!(font_set_identity(&first), font_set_identity(&second));
    }
}
