[package]
name = "umber-fetch"
version.workspace = true
edition.workspace = true

[dependencies]
sha2.workspace = true
tempfile.workspace = true
tex-state = { path = "../tex-state" }
umber-distribution = { path = "../umber-distribution" }
ureq = { version = "3.3", default-features = false, features = ["rustls"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1", features = ["fs"] }

[lints]
workspace = true
