[package]
name = "tex-exec"
version.workspace = true
edition.workspace = true

[features]
profiling = ["tex-command/profiling", "tex-state/profiling"]

[dependencies]
ahash.workspace = true
smallvec.workspace = true
tex-arith = { path = "../tex-arith" }
tex-command = { path = "../tex-command" }
tex-fonts = { path = "../tex-fonts" }
tex-out = { path = "../tex-out" }
tex-state = { path = "../tex-state" }
tex-typeset = { path = "../tex-typeset" }
umber-hash = { path = "../umber-hash" }

[dev-dependencies]
tempfile.workspace = true
tex-command = { path = "../tex-command" }
tex-state = { path = "../tex-state", features = ["testing"] }

test-support = { path = "../test-support" }

[lints]
workspace = true
