[package]
name = "tex-incr-benchmarks"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
criterion = "0.5"
tex-command = { path = "../../crates/tex-command" }
tex-exec = { path = "../../crates/tex-exec" }
tex-incr = { path = "../../crates/tex-incr" }
tex-state = { path = "../../crates/tex-state" }

[[bench]]
name = "accepted_edit"
harness = false
