// Native Rust translation of upstream t/bcfvalidation.t at commit 74252e6.

use bib_input::{XmlLimits, validate_control_bytes};

macro_rules! validates {
    ($name:ident, $fixture:literal) => {
        #[test]
        fn $name() {
            let bytes = include_bytes!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../../tests/corpus/bib/upstream-2.22/",
                $fixture
            ));
            validate_control_bytes(bytes, XmlLimits::default()).expect($fixture);
        }
    };
}

validates!(
    assertion_001_validation_of_tdata_annotations_bcf,
    "tdata/annotations.bcf"
);
validates!(
    assertion_002_validation_of_tdata_basic_misc_bcf,
    "tdata/basic-misc.bcf"
);
validates!(
    assertion_003_validation_of_tdata_biblatexml_bcf,
    "tdata/biblatexml.bcf"
);
validates!(
    assertion_004_validation_of_tdata_bibtex_aliases_bcf,
    "tdata/bibtex-aliases.bcf"
);
validates!(
    assertion_005_validation_of_tdata_bibtex_output_bcf,
    "tdata/bibtex-output.bcf"
);
validates!(
    assertion_006_validation_of_tdata_crossrefs_bcf,
    "tdata/crossrefs.bcf"
);
validates!(
    assertion_007_validation_of_tdata_datalists_bcf,
    "tdata/datalists.bcf"
);
validates!(
    assertion_008_validation_of_tdata_dateformats_bcf,
    "tdata/dateformats.bcf"
);
validates!(
    assertion_009_validation_of_tdata_dm_constraints_bcf,
    "tdata/dm-constraints.bcf"
);
validates!(
    assertion_010_validation_of_tdata_encoding1_bcf,
    "tdata/encoding1.bcf"
);
validates!(
    assertion_011_validation_of_tdata_encoding2_bcf,
    "tdata/encoding2.bcf"
);
validates!(
    assertion_012_validation_of_tdata_encoding3_bcf,
    "tdata/encoding3.bcf"
);
validates!(
    assertion_013_validation_of_tdata_encoding4_bcf,
    "tdata/encoding4.bcf"
);
validates!(
    assertion_014_validation_of_tdata_encoding5_bcf,
    "tdata/encoding5.bcf"
);
validates!(
    assertion_015_validation_of_tdata_encoding6_bcf,
    "tdata/encoding6.bcf"
);
validates!(
    assertion_016_validation_of_tdata_extradate_bcf,
    "tdata/extradate.bcf"
);
validates!(
    assertion_017_validation_of_tdata_extratitle_bcf,
    "tdata/extratitle.bcf"
);
validates!(
    assertion_018_validation_of_tdata_extratitleyear_bcf,
    "tdata/extratitleyear.bcf"
);
validates!(
    assertion_019_validation_of_tdata_full_bbl_bcf,
    "tdata/full-bbl.bcf"
);
validates!(
    assertion_020_validation_of_tdata_full_bibtex_bcf,
    "tdata/full-bibtex.bcf"
);
validates!(
    assertion_021_validation_of_tdata_full_dot_bcf,
    "tdata/full-dot.bcf"
);
validates!(
    assertion_022_validation_of_tdata_general_bcf,
    "tdata/general.bcf"
);
validates!(
    assertion_023_validation_of_tdata_labelalpha_bcf,
    "tdata/labelalpha.bcf"
);
validates!(
    assertion_024_validation_of_tdata_labelalphaname_bcf,
    "tdata/labelalphaname.bcf"
);
validates!(assertion_025_validation_of_tdata_maps_bcf, "tdata/maps.bcf");
validates!(
    assertion_026_validation_of_tdata_names_bcf,
    "tdata/names.bcf"
);
validates!(
    assertion_027_validation_of_tdata_names_x_bcf,
    "tdata/names_x.bcf"
);
validates!(
    assertion_028_validation_of_tdata_options_bcf,
    "tdata/options.bcf"
);
validates!(
    assertion_029_validation_of_tdata_related_bcf,
    "tdata/related.bcf"
);
validates!(
    assertion_030_validation_of_tdata_remote_files_bcf,
    "tdata/remote-files.bcf"
);
validates!(
    assertion_031_validation_of_tdata_sections_complex_bcf,
    "tdata/sections-complex.bcf"
);
validates!(
    assertion_032_validation_of_tdata_sections_bcf,
    "tdata/sections.bcf"
);
validates!(
    assertion_033_validation_of_tdata_set_dynamic_bcf,
    "tdata/set-dynamic.bcf"
);
validates!(
    assertion_034_validation_of_tdata_set_legacy_bcf,
    "tdata/set-legacy.bcf"
);
validates!(
    assertion_035_validation_of_tdata_set_static_bcf,
    "tdata/set-static.bcf"
);
validates!(
    assertion_036_validation_of_tdata_skips_bcf,
    "tdata/skips.bcf"
);
validates!(
    assertion_037_validation_of_tdata_skipsg_bcf,
    "tdata/skipsg.bcf"
);
validates!(
    assertion_038_validation_of_tdata_sort_case_bcf,
    "tdata/sort-case.bcf"
);
validates!(
    assertion_039_validation_of_tdata_sort_complex_bcf,
    "tdata/sort-complex.bcf"
);
validates!(
    assertion_040_validation_of_tdata_sort_names_bcf,
    "tdata/sort-names.bcf"
);
validates!(
    assertion_041_validation_of_tdata_sort_order_bcf,
    "tdata/sort-order.bcf"
);
validates!(
    assertion_042_validation_of_tdata_sort_uc_bcf,
    "tdata/sort-uc.bcf"
);
validates!(
    assertion_043_validation_of_tdata_translit_bcf,
    "tdata/translit.bcf"
);
validates!(
    assertion_044_validation_of_tdata_truncation_bcf,
    "tdata/truncation.bcf"
);
validates!(
    assertion_045_validation_of_tdata_uniqueness_nameparts_bcf,
    "tdata/uniqueness-nameparts.bcf"
);
validates!(
    assertion_046_validation_of_tdata_uniqueness1_bcf,
    "tdata/uniqueness1.bcf"
);
validates!(
    assertion_047_validation_of_tdata_uniqueness2_bcf,
    "tdata/uniqueness2.bcf"
);
validates!(
    assertion_048_validation_of_tdata_uniqueness3_bcf,
    "tdata/uniqueness3.bcf"
);
validates!(
    assertion_049_validation_of_tdata_uniqueness4_bcf,
    "tdata/uniqueness4.bcf"
);
validates!(
    assertion_050_validation_of_tdata_uniqueness5_bcf,
    "tdata/uniqueness5.bcf"
);
validates!(
    assertion_051_validation_of_tdata_uniqueness6_bcf,
    "tdata/uniqueness6.bcf"
);
validates!(
    assertion_052_validation_of_tdata_uniqueness7_bcf,
    "tdata/uniqueness7.bcf"
);
validates!(
    assertion_053_validation_of_tdata_xdata_bcf,
    "tdata/xdata.bcf"
);
