// Native Rust translation of upstream t/tool-bltxml.t at commit 74252e6.

use bib_engine::{BibCommand, FileProvisioner, GeneratedFile, VfsLimits, VirtualPath};

const DATA: &[u8] = include_bytes!("../../../../../tests/corpus/bib/upstream-2.22/tdata/tool.bib");
const CONFIG: &[u8] =
    include_bytes!("../../../../../tests/corpus/bib/upstream-2.22/tdata/tool-testsort.conf");
const BLTXML1: &str = r########"<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="tool.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<!-- Auto-generated by Biber::Output::biblatexml -->

<bltx:entries xmlns:bltx="http://biblatex-biber.sourceforge.net/biblatexml">
  <bltx:entry id="i3Š" entrytype="unpublished">
    <bltx:options>useprefix=false</bltx:options>
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="A">AAA</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="B">BBB</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="C">CCC</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="D">DDD</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="E">EEE</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:institution>
      <bltx:list>
        <bltx:item>REPlaCEDte</bltx:item>
        <bltx:item>early</bltx:item>
      </bltx:list>
    </bltx:institution>
    <bltx:lista>
      <bltx:list>
        <bltx:item>list test</bltx:item>
      </bltx:list>
    </bltx:lista>
    <bltx:listb>
      <bltx:list>
        <bltx:item>late</bltx:item>
        <bltx:item>early</bltx:item>
      </bltx:list>
    </bltx:listb>
    <bltx:location>
      <bltx:list>
        <bltx:item>one</bltx:item>
        <bltx:item>two</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:abstract>Some abstract %50 of which is useless</bltx:abstract>
    <bltx:note>i3Š</bltx:note>
    <bltx:title>Š title</bltx:title>
    <bltx:userb>test</bltx:userb>
    <bltx:date>2003</bltx:date>
  </bltx:entry>
  <bltx:entry id="xd1" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="E">Ellington</bltx:namepart>
        <bltx:namepart type="given">
          <bltx:namepart initial="E">Edward</bltx:namepart>
          <bltx:namepart initial="P">Paul</bltx:namepart>
        </bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:location>
      <bltx:list>
        <bltx:item>New York</bltx:item>
        <bltx:item>London</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:publisher>
      <bltx:list>
        <bltx:item>Macmillan</bltx:item>
      </bltx:list>
    </bltx:publisher>
    <bltx:note>A Note</bltx:note>
    <bltx:date>2001</bltx:date>
  </bltx:entry>
  <bltx:entry id="macmillan" entrytype="xdata">
    <bltx:ids>
      <bltx:list>
        <bltx:item>macmillanalias</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:location>
      <bltx:list>
        <bltx:item>New York</bltx:item>
        <bltx:item>London</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:publisher>
      <bltx:list>
        <bltx:item>Macmillan</bltx:item>
      </bltx:list>
    </bltx:publisher>
    <bltx:note>A Note</bltx:note>
    <bltx:date>2001</bltx:date>
  </bltx:entry>
  <bltx:entry id="macmillan:pub" entrytype="xdata">
    <bltx:ids>
      <bltx:list>
        <bltx:item>macmillan:pubALIAS</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:publisher>
      <bltx:list>
        <bltx:item>Macmillan</bltx:item>
      </bltx:list>
    </bltx:publisher>
  </bltx:entry>
  <bltx:entry id="macmillan:loc" entrytype="xdata">
    <bltx:location>
      <bltx:list>
        <bltx:item>New York</bltx:item>
        <bltx:item>London</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:note>A Note</bltx:note>
  </bltx:entry>
  <bltx:entry id="b1" entrytype="book">
    <bltx:location>
      <bltx:list>
        <bltx:item>London</bltx:item>
        <bltx:item>Edinburgh</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:mainsubtitle>Mainsubtitle</bltx:mainsubtitle>
    <bltx:maintitle>Maintitle</bltx:maintitle>
    <bltx:maintitleaddon>Maintitleaddon</bltx:maintitleaddon>
    <bltx:title>Booktitle</bltx:title>
    <bltx:date>1999</bltx:date>
    <bltx:annotation field="title" name="default" literal="0">ann1, ann2</bltx:annotation>
    <bltx:annotation field="location" name="default" item="1" literal="0">ann1</bltx:annotation>
    <bltx:annotation field="location" name="default" item="2" literal="0">ann2</bltx:annotation>
  </bltx:entry>
  <bltx:entry id="mv1" entrytype="mvbook">
    <bltx:ids>
      <bltx:list>
        <bltx:item>mvalias</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:subtitle>Mainsubtitle</bltx:subtitle>
    <bltx:title>Maintitle</bltx:title>
    <bltx:titleaddon>Maintitleaddon</bltx:titleaddon>
  </bltx:entry>
  <bltx:entry id="dt1" entrytype="book">
    <bltx:date>
      <bltx:start>2004-04-25T14:34:00</bltx:start>
      <bltx:end>2004-04-05T14:37:06</bltx:end>
    </bltx:date>
    <bltx:date type="event">
      <bltx:start>2004-04-25T14:34:00+05:00</bltx:start>
      <bltx:end>2004-04-05T15:34:00+05:00</bltx:end>
    </bltx:date>
    <bltx:date type="orig">
      <bltx:start>2004-04-25T14:34:00Z</bltx:start>
      <bltx:end>2004-04-05T14:34:05Z</bltx:end>
    </bltx:date>
    <bltx:date type="url">
      <bltx:start>2004-04-25T14:34:00</bltx:start>
      <bltx:end>2004-04-05T15:00:00</bltx:end>
    </bltx:date>
  </bltx:entry>
  <bltx:entry id="m1" entrytype="article">
    <bltx:date>2017</bltx:date>
  </bltx:entry>
  <bltx:entry id="badcr1" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="F">Foo</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:title>Foo</bltx:title>
    <bltx:date>2019</bltx:date>
  </bltx:entry>
  <bltx:entry id="badcr2" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="B">Bar</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:title>Bar</bltx:title>
    <bltx:date>2019</bltx:date>
  </bltx:entry>
  <bltx:entry id="gxd1" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="S">Smith</bltx:namepart>
        <bltx:namepart type="given" initial="S">Simon</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="B">Bloom</bltx:namepart>
        <bltx:namepart type="given" initial="B">Brian</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:names type="editor">
      <bltx:name>
        <bltx:namepart type="family" initial="F">Frill</bltx:namepart>
        <bltx:namepart type="given" initial="F">Frank</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:names type="translator">
      <bltx:name xdata="gxd2_author_3" />
    </bltx:names>
    <bltx:lista>
      <bltx:list>
        <bltx:item xdata="gxd3_location_5" />
      </bltx:list>
    </bltx:lista>
    <bltx:location>
      <bltx:list>
        <bltx:item>A</bltx:item>
        <bltx:item>B</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:organization>
      <bltx:list>
        <bltx:item xdata="gxd2_author_3" />
      </bltx:list>
    </bltx:organization>
    <bltx:publisher>
      <bltx:list>
        <bltx:item xdata="gxd2" />
      </bltx:list>
    </bltx:publisher>
    <bltx:addendum xdata="missing" />
    <bltx:note xdata="gxd2_note" />
    <bltx:title>Some title</bltx:title>
  </bltx:entry>
  <bltx:entry id="gxd2" entrytype="xdata">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="B">Bloom</bltx:namepart>
        <bltx:namepart type="given" initial="B">Brian</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="A">Anderson</bltx:namepart>
        <bltx:namepart type="given" initial="A">Arthur</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:names type="editor">
      <bltx:name>
        <bltx:namepart type="family" initial="W">Wool</bltx:namepart>
        <bltx:namepart type="given" initial="W">William</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="F">Frill</bltx:namepart>
        <bltx:namepart type="given" initial="F">Frank</bltx:namepart>
      </bltx:name>
    </bltx:names>
  </bltx:entry>
  <bltx:entry id="gxd3" entrytype="xdata">
    <bltx:location>
      <bltx:list>
        <bltx:item>A</bltx:item>
        <bltx:item>C</bltx:item>
      </bltx:list>
    </bltx:location>
  </bltx:entry>
  <bltx:entry id="gxd4" entrytype="xdata">
    <bltx:names type="editor">
      <bltx:name>
        <bltx:namepart type="family" initial="F">Frill</bltx:namepart>
        <bltx:namepart type="given" initial="F">Frank</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:title>Some title</bltx:title>
  </bltx:entry>
  <bltx:entry id="bo1" entrytype="book">
    <bltx:ids>
      <bltx:list>
        <bltx:item>box1</bltx:item>
        <bltx:item>box2</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="S">Smith</bltx:namepart>
        <bltx:namepart type="given" initial="S">Simon</bltx:namepart>
      </bltx:name>
    </bltx:names>
  </bltx:entry>
  <bltx:entry id="ld1" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="A">AAA</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="B">BBB</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="C">CCC</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="D">DDD</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="E">EEE</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:publisher>
      <bltx:list>
        <bltx:item>Publisher</bltx:item>
      </bltx:list>
    </bltx:publisher>
    <bltx:title>A title</bltx:title>
    <bltx:date>2003-04</bltx:date>
  </bltx:entry>
</bltx:entries>
"########;
const BLTXML2: &str = r########"<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="tool.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<!-- Auto-generated by Biber::Output::biblatexml -->

<bltx:entries xmlns:bltx="http://biblatex-biber.sourceforge.net/biblatexml">
  <bltx:entry id="i3Š" entrytype="unpublished">
    <bltx:options>useprefix=false</bltx:options>
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="A">AAA</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="B">BBB</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="C">CCC</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="D">DDD</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="E">EEE</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:institution>
      <bltx:list>
        <bltx:item>REPlaCEDte</bltx:item>
        <bltx:item>early</bltx:item>
      </bltx:list>
    </bltx:institution>
    <bltx:lista>
      <bltx:list>
        <bltx:item>list test</bltx:item>
      </bltx:list>
    </bltx:lista>
    <bltx:listb>
      <bltx:list>
        <bltx:item>late</bltx:item>
        <bltx:item>early</bltx:item>
      </bltx:list>
    </bltx:listb>
    <bltx:location>
      <bltx:list>
        <bltx:item>one</bltx:item>
        <bltx:item>two</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:abstract>Some abstract %50 of which is useless</bltx:abstract>
    <bltx:note>i3Š</bltx:note>
    <bltx:title>Š title</bltx:title>
    <bltx:userb>test</bltx:userb>
    <bltx:date>2003</bltx:date>
  </bltx:entry>
  <bltx:entry id="xd1" entrytype="book">
    <bltx:xdata>
      <bltx:list>
        <bltx:item>macmillanalias</bltx:item>
      </bltx:list>
    </bltx:xdata>
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="E">Ellington</bltx:namepart>
        <bltx:namepart type="given">
          <bltx:namepart initial="E">Edward</bltx:namepart>
          <bltx:namepart initial="P">Paul</bltx:namepart>
        </bltx:namepart>
      </bltx:name>
    </bltx:names>
  </bltx:entry>
  <bltx:entry id="macmillan" entrytype="xdata">
    <bltx:ids>
      <bltx:list>
        <bltx:item>macmillanalias</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:xdata>
      <bltx:list>
        <bltx:item>macmillan:pubALIAS</bltx:item>
        <bltx:item>macmillan:loc</bltx:item>
      </bltx:list>
    </bltx:xdata>
    <bltx:date>2001</bltx:date>
  </bltx:entry>
  <bltx:entry id="macmillan:pub" entrytype="xdata">
    <bltx:ids>
      <bltx:list>
        <bltx:item>macmillan:pubALIAS</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:publisher>
      <bltx:list>
        <bltx:item>Macmillan</bltx:item>
      </bltx:list>
    </bltx:publisher>
  </bltx:entry>
  <bltx:entry id="macmillan:loc" entrytype="xdata">
    <bltx:location>
      <bltx:list>
        <bltx:item>New York</bltx:item>
        <bltx:item>London</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:note>A Note</bltx:note>
  </bltx:entry>
  <bltx:entry id="b1" entrytype="book">
    <bltx:location>
      <bltx:list>
        <bltx:item>London</bltx:item>
        <bltx:item>Edinburgh</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:mainsubtitle>Mainsubtitle</bltx:mainsubtitle>
    <bltx:maintitle>Maintitle</bltx:maintitle>
    <bltx:maintitleaddon>Maintitleaddon</bltx:maintitleaddon>
    <bltx:title>Booktitle</bltx:title>
    <bltx:date>1999</bltx:date>
    <bltx:annotation field="title" name="default" literal="0">ann1, ann2</bltx:annotation>
    <bltx:annotation field="location" name="default" item="1" literal="0">ann1</bltx:annotation>
    <bltx:annotation field="location" name="default" item="2" literal="0">ann2</bltx:annotation>
  </bltx:entry>
  <bltx:entry id="mv1" entrytype="mvbook">
    <bltx:ids>
      <bltx:list>
        <bltx:item>mvalias</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:subtitle>Mainsubtitle</bltx:subtitle>
    <bltx:title>Maintitle</bltx:title>
    <bltx:titleaddon>Maintitleaddon</bltx:titleaddon>
  </bltx:entry>
  <bltx:entry id="dt1" entrytype="book">
    <bltx:date>
      <bltx:start>2004-04-25T14:34:00</bltx:start>
      <bltx:end>2004-04-05T14:37:06</bltx:end>
    </bltx:date>
    <bltx:date type="event">
      <bltx:start>2004-04-25T14:34:00+05:00</bltx:start>
      <bltx:end>2004-04-05T15:34:00+05:00</bltx:end>
    </bltx:date>
    <bltx:date type="orig">
      <bltx:start>2004-04-25T14:34:00Z</bltx:start>
      <bltx:end>2004-04-05T14:34:05Z</bltx:end>
    </bltx:date>
    <bltx:date type="url">
      <bltx:start>2004-04-25T14:34:00</bltx:start>
      <bltx:end>2004-04-05T15:00:00</bltx:end>
    </bltx:date>
  </bltx:entry>
  <bltx:entry id="m1" entrytype="article">
    <bltx:date>2017</bltx:date>
  </bltx:entry>
  <bltx:entry id="badcr1" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="F">Foo</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:title>Foo</bltx:title>
    <bltx:date>2019</bltx:date>
  </bltx:entry>
  <bltx:entry id="badcr2" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="B">Bar</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:title>Bar</bltx:title>
    <bltx:date>2019</bltx:date>
  </bltx:entry>
  <bltx:entry id="gxd1" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="S">Smith</bltx:namepart>
        <bltx:namepart type="given" initial="S">Simon</bltx:namepart>
      </bltx:name>
      <bltx:name xdata="gxd2+author+1" />
    </bltx:names>
    <bltx:names type="editor">
      <bltx:name xdata="gxd2+editor+2" />
    </bltx:names>
    <bltx:names type="translator">
      <bltx:name xdata="gxd2+author+3" />
    </bltx:names>
    <bltx:lista>
      <bltx:list>
        <bltx:item xdata="gxd3+location+5" />
      </bltx:list>
    </bltx:lista>
    <bltx:location>
      <bltx:list>
        <bltx:item xdata="gxd3+location+1" />
        <bltx:item>B</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:organization>
      <bltx:list>
        <bltx:item xdata="gxd2+author+3" />
      </bltx:list>
    </bltx:organization>
    <bltx:publisher>
      <bltx:list>
        <bltx:item xdata="gxd2" />
      </bltx:list>
    </bltx:publisher>
    <bltx:addendum xdata="missing" />
    <bltx:note xdata="gxd2+note" />
    <bltx:title xdata="gxd4+title" />
  </bltx:entry>
  <bltx:entry id="gxd2" entrytype="xdata">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="B">Bloom</bltx:namepart>
        <bltx:namepart type="given" initial="B">Brian</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="A">Anderson</bltx:namepart>
        <bltx:namepart type="given" initial="A">Arthur</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:names type="editor">
      <bltx:name>
        <bltx:namepart type="family" initial="W">Wool</bltx:namepart>
        <bltx:namepart type="given" initial="W">William</bltx:namepart>
      </bltx:name>
      <bltx:name xdata="gxd4+editor+1" />
    </bltx:names>
  </bltx:entry>
  <bltx:entry id="gxd3" entrytype="xdata">
    <bltx:location>
      <bltx:list>
        <bltx:item>A</bltx:item>
        <bltx:item>C</bltx:item>
      </bltx:list>
    </bltx:location>
  </bltx:entry>
  <bltx:entry id="gxd4" entrytype="xdata">
    <bltx:names type="editor">
      <bltx:name>
        <bltx:namepart type="family" initial="F">Frill</bltx:namepart>
        <bltx:namepart type="given" initial="F">Frank</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:title>Some title</bltx:title>
  </bltx:entry>
  <bltx:entry id="bo1" entrytype="book">
    <bltx:ids>
      <bltx:list>
        <bltx:item>box1</bltx:item>
        <bltx:item>box2</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="S">Smith</bltx:namepart>
        <bltx:namepart type="given" initial="S">Simon</bltx:namepart>
      </bltx:name>
    </bltx:names>
  </bltx:entry>
  <bltx:entry id="ld1" entrytype="book">
    <bltx:names type="author">
      <bltx:name>
        <bltx:namepart type="family" initial="A">AAA</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="B">BBB</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="C">CCC</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="D">DDD</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="E">EEE</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:publisher>
      <bltx:list>
        <bltx:item>Publisher</bltx:item>
      </bltx:list>
    </bltx:publisher>
    <bltx:title>A title</bltx:title>
    <bltx:date>2003-04</bltx:date>
  </bltx:entry>
</bltx:entries>
"########;

fn run() -> (Vec<u8>, Vec<String>) {
    let command = BibCommand::parse([
        "--tool",
        "--configfile=tool-testsort.conf",
        "--output-format=biblatexml",
        "--output-file=actual.bltxml",
        "tool.bib",
    ])
    .unwrap();
    let mut files = FileProvisioner::new(VfsLimits::default()).unwrap();
    files
        .register_user(VirtualPath::user("tool.bib").unwrap(), DATA.to_vec())
        .unwrap();
    files
        .register_user(
            VirtualPath::user("tool-testsort.conf").unwrap(),
            CONFIG.to_vec(),
        )
        .unwrap();
    files
        .register_user(
            VirtualPath::user(".umber/tool.bcf").unwrap(),
            command.tool_control().unwrap(),
        )
        .unwrap();
    let output = command.execute(&files.snapshot());
    let order = output
        .result()
        .and_then(|result| result.document().sections().next())
        .and_then(|section| section.lists().next())
        .map(|list| {
            list.entries()
                .map(|entry| entry.as_str().to_owned())
                .collect()
        })
        .unwrap_or_default();
    let bytes = output
        .result()
        .and_then(|result| result.files().next())
        .map(GeneratedFile::bytes)
        .unwrap_or_default()
        .to_vec();
    (bytes, order)
}

#[test]
#[ignore = "xfail: native BibLaTeXML serializer does not yet reproduce Biber tool output"]
fn assertion_001_bltxml_tool_mode_1() {
    assert_eq!(run().0, BLTXML1.as_bytes());
}

#[test]
#[ignore = "xfail: native tool-mode sorting does not yet reproduce Biber ordering"]
fn assertion_002_tool_mode_sorting() {
    assert_eq!(
        run().1,
        [
            "b1",
            "macmillan",
            "dt1",
            "m1",
            "macmillan:pub",
            "macmillan:loc",
            "mv1",
            "gxd3",
            "gxd4",
            "i3Š",
            "ld1",
            "badcr2",
            "gxd2",
            "xd1",
            "badcr1",
            "bo1",
            "gxd1"
        ]
    );
}

#[test]
#[ignore = "xfail: native tool options do not yet expose unresolved xdata output"]
fn assertion_003_bltxml_tool_mode_2() {
    assert_eq!(run().0, BLTXML2.as_bytes());
}
