// Native Rust translation of upstream t/tool-bltxml-inout.t at commit 74252e6.

use bib_engine::{BibCommand, FileProvisioner, GeneratedFile, VfsLimits, VirtualPath};

const DATA: &[u8] =
    include_bytes!("../../../../../tests/corpus/bib/upstream-2.22/tdata/biblatexml.bltxml");
const CONFIG: &[u8] =
    include_bytes!("../../../../../tests/corpus/bib/upstream-2.22/tdata/tool-test.conf");
const BLTXML1: &str = r########"<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="biblatexml.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<!-- Auto-generated by Biber::Output::biblatexml -->

<bltx:entries xmlns:bltx="http://biblatex-biber.sourceforge.net/biblatexml">
  <bltx:entry id="bltx1" entrytype="book">
    <bltx:ids>
      <bltx:list>
        <bltx:item>bltx1a1</bltx:item>
        <bltx:item>bltx1a2</bltx:item>
      </bltx:list>
    </bltx:ids>
    <bltx:options>useprefix=false</bltx:options>
    <bltx:names type="afterword">
      <bltx:name gender="sm">
        <bltx:namepart type="family" initial="B">Brown</bltx:namepart>
        <bltx:namepart type="given" initial="J">John</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:names type="author" morenames="1" useprefix="true">
      <bltx:name gender="sm">
        <bltx:namepart type="family" initial="Б">Булгаков</bltx:namepart>
        <bltx:namepart type="given">
          <bltx:namepart initial="П">Павел</bltx:namepart>
          <bltx:namepart initial="Г">Георгиевич</bltx:namepart>
        </bltx:namepart>
        <bltx:namepart type="prefix" initial="v">von</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="Р">Розенфельд</bltx:namepart>
        <bltx:namepart type="given">
          <bltx:namepart initial="Б-Z">Борис-ZZ</bltx:namepart>
          <bltx:namepart initial="A">Aбрамович</bltx:namepart>
        </bltx:namepart>
        <bltx:namepart type="prefix" initial="v">von</bltx:namepart>
      </bltx:name>
      <bltx:name>
        <bltx:namepart type="family" initial="A">Aхмедов</bltx:namepart>
        <bltx:namepart type="given">
          <bltx:namepart initial="A">Ашраф</bltx:namepart>
          <bltx:namepart initial="А">Ахмедович</bltx:namepart>
        </bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:names type="editor">
      <bltx:name gender="sm">
        <bltx:namepart type="family" initial="S">Smith</bltx:namepart>
        <bltx:namepart type="given" initial="P">Paul</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:names type="translator">
      <bltx:name gender="sm">
        <bltx:namepart type="family" initial="B">Brown</bltx:namepart>
        <bltx:namepart type="given" initial="J">John</bltx:namepart>
      </bltx:name>
    </bltx:names>
    <bltx:language>
      <bltx:list>
        <bltx:item>russian</bltx:item>
      </bltx:list>
    </bltx:language>
    <bltx:location>
      <bltx:list>
        <bltx:item>Москва</bltx:item>
      </bltx:list>
    </bltx:location>
    <bltx:publisher>
      <bltx:list>
        <bltx:item>Наука</bltx:item>
      </bltx:list>
    </bltx:publisher>
    <bltx:pagetotal>240</bltx:pagetotal>
    <bltx:series>Научно-биографическая литература</bltx:series>
    <bltx:title>Мухаммад ибн муса ал-Хорезми. Около 783 – около 850</bltx:title>
    <bltx:usera>usera</bltx:usera>
    <bltx:userb>userb</bltx:userb>
    <bltx:userc>userc</bltx:userc>
    <bltx:userd>userd</bltx:userd>
    <bltx:usere>a</bltx:usere>
    <bltx:pages>
      <bltx:list>
        <bltx:item>
          <bltx:start>1</bltx:start>
          <bltx:end>10</bltx:end>
        </bltx:item>
        <bltx:item>
          <bltx:start>30</bltx:start>
          <bltx:end>34</bltx:end>
        </bltx:item>
      </bltx:list>
    </bltx:pages>
    <bltx:date>198X</bltx:date>
    <bltx:date type="event">
      <bltx:start>1990-05-16</bltx:start>
      <bltx:end>1990-05-17</bltx:end>
    </bltx:date>
    <bltx:date type="orig">-356</bltx:date>
    <bltx:date type="url">
      <bltx:start>1991~</bltx:start>
      <bltx:end></bltx:end>
    </bltx:date>
    <bltx:annotation field="author" name="alt" literal="0">names-ann3</bltx:annotation>
    <bltx:annotation field="author" name="default" literal="0">names-ann</bltx:annotation>
    <bltx:annotation field="language" name="default" literal="0">list-ann1</bltx:annotation>
    <bltx:annotation field="title" name="default" literal="0">field-ann1</bltx:annotation>
    <bltx:annotation field="author" name="default" item="1" literal="0">name-ann1</bltx:annotation>
    <bltx:annotation field="author" name="default" item="3" literal="0">name-ann2</bltx:annotation>
    <bltx:annotation field="language" name="default" item="1" literal="0">item-ann1</bltx:annotation>
    <bltx:annotation field="author" name="default" item="1" part="given" literal="1">namepart-ann1</bltx:annotation>
    <bltx:annotation field="author" name="default" item="2" part="family" literal="0">namepart-ann2</bltx:annotation>
  </bltx:entry>
</bltx:entries>
"########;

fn run() -> Vec<u8> {
    let command = BibCommand::parse([
        "--tool",
        "--configfile=tool-test.conf",
        "--output-format=biblatexml",
        "--output-file=actual.bltxml",
        "biblatexml.bltxml",
    ])
    .unwrap();
    let mut files = FileProvisioner::new(VfsLimits::default()).unwrap();
    files
        .register_user(
            VirtualPath::user("biblatexml.bltxml").unwrap(),
            DATA.to_vec(),
        )
        .unwrap();
    files
        .register_user(
            VirtualPath::user("tool-test.conf").unwrap(),
            CONFIG.to_vec(),
        )
        .unwrap();
    files
        .register_user(
            VirtualPath::user(".umber/tool.bcf").unwrap(),
            command.tool_control().unwrap(),
        )
        .unwrap();
    command
        .execute(&files.snapshot())
        .result()
        .and_then(|result| result.files().next())
        .map(GeneratedFile::bytes)
        .unwrap_or_default()
        .to_vec()
}

#[test]
#[ignore = "xfail: native BibLaTeXML round-trip serializer does not yet reproduce Biber output"]
fn assertion_001_bltxml_in_and_out_tool_mode_1() {
    assert_eq!(run(), BLTXML1.as_bytes());
}
