#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

text_areas=(hello lexer expand lexer_dynamic exec etex_exec typeset tex_exec tex_exec_io)
dvi_areas=(dvi page math align leaders)
pdf_area=pdf
e2e_area=e2e
bib_area=bib
bibtex_area=bibtex
readonly bib_upstream_commit=74252e608e5f8115375c532eb25416430a9f52eb

target_dir="${CARGO_TARGET_DIR:-target}"
if [[ "$target_dir" != /* ]]; then
  target_dir="${repo_root}/${target_dir}"
fi
refexec_bin="${target_dir}/debug/refexec"
fixturegen_bin="${target_dir}/debug/fixturegen"
umber_bin="${target_dir}/debug/umber"
parity_harness_bin="${target_dir}/debug/parity-harness"
refexec_built=0
fixturegen_built=0
umber_built=0
parity_harness_built=0
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1783604160}"
export FORCE_SOURCE_DATE="${FORCE_SOURCE_DATE:-1}"

usage() {
  cat <<'EOF'
usage:
  scripts/regen-fixtures.sh --incremental
  scripts/regen-fixtures.sh --all
  scripts/regen-fixtures.sh --area AREA
  scripts/regen-fixtures.sh --case AREA/CASE
  scripts/regen-fixtures.sh --case AREA CASE

Fixture areas:
  text/native: hello lexer expand lexer_dynamic exec etex_exec typeset tex_exec tex_exec_io
  DVI:         dvi page math align leaders
  PDF:         pdf  (pinned pdfTeX structure plus exact Poppler grayscale pixels)
  bibliography: bib  (verbatim pinned upstream test data and SHA-256 manifest)
  classic BibTeX: bibtex  (pinned merged WEB2C program, inventory, BBL, and BLG)
  end-to-end:  e2e  (story, gentle, trip, and e-trip local DVI oracles)
  live check:  fonts  (runs the tftopl cross-check; it does not rewrite fixtures)

Reference tools:
  Text and DVI reference regeneration requires pdftex or tex on PATH, or
  UMBER_REF_TEX=/absolute/path/to/pdftex. Text/native regeneration builds and
  runs the workspace fixturegen tool; DVI regeneration builds and runs the
  workspace refexec tool and copies pinned CM TFMs from
  crates/tex-fonts/tests/fixtures/cm plus area-local support files.

  End-to-end regeneration writes gitignored local oracles and requires the
  fetched external inputs. Story and Gentle use parity-harness to stage live
  reference TeX consistently; TRIP
  performs the official two-phase workload with pdfTeX and commits the DVI
  generated by that local run. Set UMBER_REF_PDFTEX to select pdfTeX.

  The fonts live check requires tftopl on PATH, or
  UMBER_REF_TFTOPL=/absolute/path/to/tftopl.

  PDF regeneration requires pdfTeX 1.40.27 and pdftoppm 25.08.0. Set
  UMBER_REF_PDFTEX and UMBER_PDF_RENDERER to select their absolute paths.

  Regeneration pins SOURCE_DATE_EPOCH by default so Umber and the reference
  TeX observe the same job-start clock. Set SOURCE_DATE_EPOCH explicitly to
  override the default fixed timestamp.

  Bibliography fixture regeneration requires a local clone of the upstream
  repository. Set UMBER_REF_BIBER_SOURCE=/absolute/path/to/clone. The script
  exports commit 74252e608e5f8115375c532eb25416430a9f52eb directly from Git;
  the clone's checkout and working-tree modifications are ignored.

  Classic BibTeX regeneration builds the hash-pinned TeX Live 2025 Web2C
  source cached under third_party/texlive-source, verifies the merged
  bibtex.web+bibtex.ch program, configuration, and executable identities, and
  runs the committed cases in an empty environment. Set
  UMBER_REF_TEXLIVE_SOURCE to select an equivalent cache root containing the
  pinned archive, src, and build directories.
EOF
}

die() {
  printf 'regen-fixtures: %s\n' "$*" >&2
  exit 2
}

contains_area() {
  local needle="$1"
  shift
  local area
  for area in "$@"; do
    if [[ "$area" == "$needle" ]]; then
      return 0
    fi
  done
  return 1
}

is_text_area() {
  contains_area "$1" "${text_areas[@]}"
}

is_dvi_area() {
  contains_area "$1" "${dvi_areas[@]}"
}

is_known_area() {
  is_text_area "$1" || is_dvi_area "$1" || \
    [[ "$1" == "$pdf_area" || "$1" == "$e2e_area" || \
       "$1" == "$bib_area" || "$1" == "$bibtex_area" || "$1" == "fonts" ]]
}

test_command_for_area() {
  local area="$1"
  case "$area" in
    hello)
      printf '%s\n' 'cargo test -p test-support hello_fixture_is_committed'
      ;;
    lexer)
      printf '%s\n' 'cargo test -p umber --test it lex_dump_prints_stable_token_format_for_corpus'
      ;;
    expand)
      printf '%s\n' 'cargo test -p umber --test it expand_dump_prints_stable_token_format_for_corpus'
      ;;
    lexer_dynamic)
      printf '%s\n' 'cargo test -p umber --test it lexer_dynamic_corpus_covers_mutable_input_state'
      ;;
    exec)
      printf '%s\n' 'cargo test -p umber --test it run_exec_corpus_matches_committed_diagnostics'
      ;;
    etex_exec)
      printf '%s\n' 'cargo test -p umber --test it run_etex_exec_corpus_matches_committed_diagnostics'
      ;;
    typeset)
      printf '%s\n' 'cargo test -p umber --test it run_typeset_corpus_matches_committed_box_dumps'
      ;;
    tex_exec)
      printf '%s\n' 'cargo test -p tex-exec --lib grouping_parity'
      ;;
    tex_exec_io)
      printf '%s\n' 'cargo test -p tex-exec --lib io::'
      ;;
    dvi)
      printf '%s\n' 'cargo test -p umber --test it run_dvi_corpus_matches_committed_dvi'
      ;;
    page)
      printf '%s\n' 'cargo test -p umber --test it run_page_corpus_matches_committed_dvi'
      ;;
    math)
      printf '%s\n' 'cargo test -p umber --test it run_math_corpus_matches_committed_dvi'
      ;;
    align)
      printf '%s\n' 'cargo test -p umber --test it run_align_corpus_matches_committed_dvi'
      ;;
    leaders)
      printf '%s\n' 'cargo test -p umber --test it run_leaders_corpus_matches_committed_dvi'
      ;;
    pdf)
      printf '%s\n' 'cargo test -p umber --test it pdf_parity'
      ;;
    bib)
      printf '%s\n' 'cargo test -p bib-engine --test it fixture_manifest_is_complete_and_pinned'
      ;;
    bibtex)
      printf '%s\n' 'cargo test -p bib-engine --test it classic_fixture_manifest_and_inventory_are_complete_and_pinned'
      ;;
    *)
      die "unknown fixture area: ${area}"
      ;;
  esac
}

run_command() {
  local description="$1"
  shift
  printf '%s\n' "$description" >&2
  "$@"
}

build_refexec_once() {
  if [[ "$refexec_built" -eq 0 ]]; then
    run_command 'Building refexec' cargo build -p refexec
    refexec_built=1
  fi
}

build_fixturegen_once() {
  if [[ "$fixturegen_built" -eq 0 ]]; then
    run_command 'Building fixturegen' cargo build --manifest-path tools/fixturegen/Cargo.toml --target-dir "$target_dir"
    fixturegen_built=1
  fi
}

build_umber_once() {
  if [[ "$umber_built" -eq 0 ]]; then
    run_command 'Building umber' cargo build -p umber
    umber_built=1
  fi
}

build_parity_harness_once() {
  if [[ "$parity_harness_built" -eq 0 ]]; then
    run_command 'Building parity-harness' cargo build -p parity-harness --features reference-tools
    parity_harness_built=1
  fi
}

fixturegen_needs_umber() {
  case "$1" in
    lexer|expand)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

copy_dvi_inputs() {
  local area="$1"
  local case_name="$2"
  local case_dir="$3"
  local corpus_dir="${repo_root}/tests/corpus/${area}"
  local cm_tfm_dir="${repo_root}/crates/tex-fonts/tests/fixtures/cm"
  local tfm
  local support
  local support_name

  cp "${corpus_dir}/${case_name}" "${case_dir}/${case_name}"
  for tfm in cmr10.tfm cmmi10.tfm cmsy10.tfm cmex10.tfm; do
    cp "${cm_tfm_dir}/${tfm}" "${case_dir}/${tfm}"
    dvi_extra_inputs+=(--extra-input "$tfm")
  done
  while IFS= read -r support; do
    support_name="$(basename "$support")"
    cp "$support" "${case_dir}/${support_name}"
    dvi_extra_inputs+=(--extra-input "$support_name")
  done < <(find "$corpus_dir" -maxdepth 1 -type f ! -name '*.tex' ! -name '*.expected.*' | sort)
}

regen_dvi_case() {
  local area="$1"
  local case="$2"
  local corpus_dir="${repo_root}/tests/corpus/${area}"
  local source="${corpus_dir}/${case}.tex"
  local fixture="${corpus_dir}/${case}.expected.dvi"
  local case_name="${case}.tex"
  local tmp_root
  local case_dir
  local ref_dvi
  local compare_status
  local ini_arg=""

  [[ -f "$source" ]] || die "missing DVI source: tests/corpus/${area}/${case}.tex"

  build_refexec_once
  tmp_root="$(mktemp -d)"
  case_dir="${tmp_root}/${area}-${case}"
  mkdir -p "$case_dir"
  dvi_extra_inputs=()
  copy_dvi_inputs "$area" "$case_name" "$case_dir"
  if [[ "$area" == "math" ]]; then
    ini_arg="--ini"
  fi

  printf 'Regenerating DVI fixture %s/%s\n' "$area" "$case" >&2
  if [[ -n "$ini_arg" ]]; then
    (
      cd "$case_dir"
      "$refexec_bin" "$case_name" --dvi "$ini_arg" "${dvi_extra_inputs[@]}"
    )
  else
    (
      cd "$case_dir"
      "$refexec_bin" "$case_name" --dvi "${dvi_extra_inputs[@]}"
    )
  fi
  ref_dvi="${case_dir}/${case}.ref.dvi"
  [[ -f "$ref_dvi" ]] || die "reference DVI was not written for ${area}/${case}"

  if [[ -f "$fixture" ]]; then
    set +e
    if [[ -n "$ini_arg" ]]; then
      (
        cd "$case_dir"
        "$refexec_bin" "$case_name" --compare-dvi "$fixture" \
          "$ini_arg" "${dvi_extra_inputs[@]}"
      )
    else
      (
        cd "$case_dir"
        "$refexec_bin" "$case_name" --compare-dvi "$fixture" \
          "${dvi_extra_inputs[@]}"
      )
    fi
    compare_status=$?
    set -e
    if [[ "$compare_status" -eq 0 ]]; then
      printf 'DVI fixture unchanged: %s/%s\n' "$area" "$case" >&2
      rm -rf "$tmp_root"
      return
    fi
  fi

  cp "$ref_dvi" "$fixture"
  printf 'DVI fixture updated: %s\n' "${fixture#"$repo_root"/}" >&2
  rm -rf "$tmp_root"
}

validate_dvi_area() {
  local area="$1"
  local command_string
  command_string="$(test_command_for_area "$area")"
  # shellcheck disable=SC2086
  run_command "Validating ${area} DVI fixtures" $command_string
}

validate_e2e_case() {
  local case="$1"
  run_command "Validating e2e/${case} DVI fixture" \
    cargo test -p umber --test it "e2e_conformance_${case}" -- --nocapture
}

regen_e2e_case() {
  local case="$1"
  local fixture="${repo_root}/tests/corpus/e2e/${case}.expected.dvi"
  mkdir -p "$(dirname "$fixture")"
  case "$case" in
    story|gentle)
      [[ -f "${repo_root}/third_party/corpus/${case}.tex" ]] || \
        die "missing third_party/corpus/${case}.tex; run scripts/setup-conformance-tests.sh"
      [[ -f "${repo_root}/third_party/corpus/plain.tex" ]] || \
        die "missing third_party/corpus/plain.tex; run scripts/setup-conformance-tests.sh"
      [[ -f "${repo_root}/third_party/hyphen/hyphen.tex" ]] || \
        die "missing third_party/hyphen/hyphen.tex; run scripts/fetch-conformance-inputs.sh"
      build_parity_harness_once
      run_command "Regenerating e2e/${case} reference DVI fixture" \
        "$parity_harness_bin" \
        --manifest "${repo_root}/tests/corpus-manifest.txt" \
        --corpus-dir "${repo_root}/third_party/corpus" \
        --doc "${case}.tex" \
        --write-reference-fixture "$fixture"
      ;;
    trip)
      regen_trip_pdftex_fixture "$fixture"
      ;;
    etrip)
      regen_etrip_pdftex_fixture "$fixture"
      ;;
    *)
      die "unknown e2e fixture case: ${case}"
      ;;
  esac
  validate_e2e_case "$case"
}

regen_trip_pdftex_fixture() {
  local fixture="$1"
  local pdftex="${UMBER_REF_PDFTEX:-}"
  local tmp_root
  local status
  if [[ -z "$pdftex" ]]; then
    pdftex="$(command -v pdftex || true)"
  fi
  [[ -n "$pdftex" && -x "$pdftex" ]] || \
    die "could not locate pdftex; set UMBER_REF_PDFTEX=/absolute/path/to/pdftex"
  [[ -f "${repo_root}/third_party/trip/trip.tex" ]] || \
    die "missing third_party/trip/trip.tex; run scripts/fetch-conformance-inputs.sh"
  [[ -f "${repo_root}/third_party/trip/trip.tfm" ]] || \
    die "missing third_party/trip/trip.tfm; run scripts/fetch-conformance-inputs.sh"

  tmp_root="$(mktemp -d)"
  cp "${repo_root}/third_party/trip/trip.tex" "$tmp_root/trip.tex"
  cp "${repo_root}/third_party/trip/trip.tfm" "$tmp_root/trip.tfm"
  set +e
  (
    cd "$tmp_root"
    printf '\n\\input trip\n' | \
      env TEXFONTS=".:${TEXFONTS:-}" "$pdftex" --progname=initex --ini \
        -interaction=nonstopmode -output-format=dvi > tripin.fot 2>&1
  )
  status=$?
  set -e
  [[ "$status" -eq 0 || "$status" -eq 1 ]] || \
    die "pdfTeX TRIP INITEX phase exited with status ${status}"
  [[ -s "$tmp_root/trip.fmt" ]] || die "pdfTeX TRIP INITEX phase did not produce trip.fmt"

  rm -f "$tmp_root/trip.dvi" "$tmp_root/trip.log" "$tmp_root/trip.fot"
  set +e
  (
    cd "$tmp_root"
    printf ' &trip trip \n' | \
      env TEXFORMATS=".:${TEXFORMATS:-}" TEXFONTS=".:${TEXFONTS:-}" \
        "$pdftex" --progname=tex -interaction=nonstopmode -output-format=dvi \
        > trip.fot 2>&1
  )
  status=$?
  set -e
  [[ "$status" -eq 0 || "$status" -eq 1 ]] || \
    die "pdfTeX format-loaded TRIP phase exited with status ${status}"
  [[ -s "$tmp_root/trip.dvi" ]] || \
    die "pdfTeX format-loaded TRIP phase did not produce trip.dvi"

  if [[ -f "$fixture" ]] && cmp -s "$tmp_root/trip.dvi" "$fixture"; then
    printf 'DVI fixture unchanged: %s\n' "${fixture#"$repo_root"/}" >&2
  else
    cp "$tmp_root/trip.dvi" "$fixture"
    printf 'DVI fixture updated: %s\n' "${fixture#"$repo_root"/}" >&2
  fi
  rm -rf "$tmp_root"
}

regen_etrip_pdftex_fixture() {
  local fixture="$1"
  local pdftex="${UMBER_REF_PDFTEX:-}"
  local tmp_root
  local status
  if [[ -z "$pdftex" ]]; then
    pdftex="$(command -v pdftex || true)"
  fi
  [[ -n "$pdftex" && -x "$pdftex" ]] || \
    die "could not locate pdftex; set UMBER_REF_PDFTEX=/absolute/path/to/pdftex"
  [[ -f "${repo_root}/third_party/trip/etrip.tex" ]] || \
    die "missing third_party/trip/etrip.tex; run scripts/fetch-conformance-inputs.sh"
  [[ -f "${repo_root}/third_party/trip/trip.tfm" ]] || \
    die "missing third_party/trip/trip.tfm; run scripts/fetch-conformance-inputs.sh"

  tmp_root="$(mktemp -d)"
  {
    printf '%s\n' \
      '%% Local e-TeX 2.6 compatibility adaptation; the official etrip.tex remains unchanged.' \
      '%% Renamed and modified as required by the e-TeX distribution terms.'
    sed 's/\\def\\etripversion{2\.0}/\\def\\etripversion{2.6}/' \
      "${repo_root}/third_party/trip/etrip.tex"
  } > "$tmp_root/etrip-local.tex"
  cp "${repo_root}/third_party/trip/trip.tfm" "$tmp_root/etrip.tfm"

  set +e
  (
    cd "$tmp_root"
    env TEXFONTS=".:${TEXFONTS:-}" "$pdftex" -etex -ini \
      -jobname=etrip -interaction=nonstopmode -output-format=dvi \
      etrip-local.tex > etripin.fot 2>&1
  )
  status=$?
  set -e
  [[ "$status" -eq 0 || "$status" -eq 1 ]] || \
    die "pdfTeX e-TRIP e-INITEX phase exited with status ${status}"
  [[ -s "$tmp_root/etrip.fmt" ]] || \
    die "pdfTeX e-TRIP e-INITEX phase did not produce etrip.fmt"

  rm -f "$tmp_root/etrip.dvi" "$tmp_root/etrip.log" "$tmp_root/etrip.out"
  set +e
  (
    cd "$tmp_root"
    env TEXFORMATS=".:${TEXFORMATS:-}" TEXFONTS=".:${TEXFONTS:-}" \
      "$pdftex" -fmt=etrip -jobname=etrip -interaction=nonstopmode \
      -output-format=dvi etrip-local.tex > etrip.fot 2>&1
  )
  status=$?
  set -e
  [[ "$status" -eq 0 || "$status" -eq 1 ]] || \
    die "pdfTeX format-loaded e-TRIP phase exited with status ${status}"
  [[ -s "$tmp_root/etrip.dvi" ]] || \
    die "pdfTeX format-loaded e-TRIP phase did not produce etrip.dvi"

  if [[ -f "$fixture" ]] && cmp -s "$tmp_root/etrip.dvi" "$fixture"; then
    printf 'DVI fixture unchanged: %s\n' "${fixture#"$repo_root"/}" >&2
  else
    cp "$tmp_root/etrip.dvi" "$fixture"
    printf 'DVI fixture updated: %s\n' "${fixture#"$repo_root"/}" >&2
  fi
  rm -rf "$tmp_root"
}

regen_e2e_area() {
  local case
  for case in story gentle trip etrip; do
    regen_e2e_case "$case"
  done
}

regen_text_area() {
  local area="$1"
  local command_string
  build_fixturegen_once
  if fixturegen_needs_umber "$area"; then
    build_umber_once
  fi
  run_command "Regenerating ${area} fixtures" \
    env UMBER_BIN="$umber_bin" "$fixturegen_bin" --area "$area"
  command_string="$(test_command_for_area "$area")"
  # shellcheck disable=SC2086
  run_command "Validating ${area} fixtures" $command_string
}

regen_dvi_area() {
  local area="$1"
  local source
  local case
  local corpus_dir="${repo_root}/tests/corpus/${area}"
  for source in "${corpus_dir}"/*.tex; do
    [[ -e "$source" ]] || continue
    case="$(basename "$source" .tex)"
    regen_dvi_case "$area" "$case"
  done
  validate_dvi_area "$area"
}

regen_pdf_area() {
  local command_string
  build_fixturegen_once
  build_umber_once
  run_command 'Regenerating pinned PDF parity fixtures' \
    env UMBER_BIN="$umber_bin" "$fixturegen_bin" --area pdf
  command_string="$(test_command_for_area pdf)"
  # shellcheck disable=SC2086
  run_command 'Validating hermetic PDF parity fixtures' $command_string
}

run_fonts_live_check() {
  build_fixturegen_once
  run_command 'Running live tftopl font cross-check' "$fixturegen_bin" --area fonts
}

sha256_file() {
  openssl dgst -sha256 -r "$1" | awk '{print $1}'
}

sha512_file() {
  openssl dgst -sha512 -r "$1" | awk '{print $1}'
}

regen_bib_area() {
  local upstream="${UMBER_REF_BIBER_SOURCE:-}"
  local fixture_dir="${repo_root}/tests/corpus/bib/upstream-2.22"
  local staged_dir
  local manifest
  local file
  local relative
  local upstream_path
  local separator=""
  local bytes
  local digest

  [[ -n "$upstream" && -d "$upstream/.git" ]] || \
    die 'set UMBER_REF_BIBER_SOURCE to a local clone of the upstream repository'
  git -C "$upstream" cat-file -e "${bib_upstream_commit}^{commit}" 2>/dev/null || \
    die "upstream clone does not contain commit ${bib_upstream_commit}"
  command -v openssl >/dev/null || die 'openssl is required to hash bibliography fixtures'

  staged_dir="$(mktemp -d)"
  git -C "$upstream" archive "$bib_upstream_commit" LICENSE t/tdata | tar -x -C "$staged_dir"
  mkdir -p "$staged_dir/tdata"
  mv "$staged_dir/LICENSE" "$staged_dir/LICENSE.Artistic-2.0"
  mv "$staged_dir/t/tdata"/* "$staged_dir/tdata/"
  rmdir "$staged_dir/t/tdata" "$staged_dir/t"

  manifest="$staged_dir/manifest.json"
  {
    printf '%s\n' '{'
    printf '%s\n' '  "schema": 1,'
    printf '%s\n' '  "upstream_repository": "https://github.com/plk/biber.git",'
    printf '  "upstream_commit": "%s",\n' "$bib_upstream_commit"
    printf '%s\n' '  "compatibility_version": "2.22 beta",'
    printf '%s\n' '  "license": "Artistic-2.0",'
    printf '%s\n' '  "files": ['
    while IFS= read -r file; do
      relative="${file#"$staged_dir"/}"
      [[ "$relative" != "manifest.json" ]] || continue
      if [[ "$relative" == "LICENSE.Artistic-2.0" ]]; then
        upstream_path="LICENSE"
      else
        upstream_path="t/${relative}"
      fi
      bytes="$(wc -c < "$file" | tr -d ' ')"
      digest="$(sha256_file "$file")"
      printf '%s' "$separator"
      printf '%s\n' '    {'
      printf '      "path": "%s",\n' "$relative"
      printf '      "upstream_path": "%s",\n' "$upstream_path"
      printf '      "bytes": %s,\n' "$bytes"
      printf '      "sha256": "%s"\n' "$digest"
      printf '%s' '    }'
      separator=$',\n'
    done < <(find "$staged_dir" -type f | LC_ALL=C sort)
    printf '\n%s\n' '  ]'
    printf '%s\n' '}'
  } > "$manifest"

  rm -rf "$fixture_dir"
  mkdir -p "$(dirname "$fixture_dir")"
  mv "$staged_dir" "$fixture_dir"
  run_command 'Validating pinned bibliography fixtures' \
    cargo test -p bib-engine --test it fixture_manifest_is_complete_and_pinned
}

regen_bibtex_area() {
  local cache_root="${UMBER_REF_TEXLIVE_SOURCE:-${repo_root}/third_party/texlive-source}"
  local source_dir="${cache_root}/src"
  local build_dir="${cache_root}/build"
  local archive="${cache_root}/texlive-20250308-source.tar.xz"
  local executable="${build_dir}/texk/web2c/bibtex"
  local fixture_dir="${repo_root}/tests/corpus/bibtex/cases/smoke"
  local tmp_root
  local case_dir
  local exit_status
  local manifest_tmp
  local expected_archive_sha512="0837c935488b96cfc8dd79f1298f283b467ab68b4163cee9cb04b79e80195982fdc5ae8a80058dc7d3e99206bfda8b3bdd11340425b08f60cbef70d5a0e22702"

  command -v openssl >/dev/null || die 'openssl is required to hash classic BibTeX fixtures'
  command -v jq >/dev/null || die 'jq is required to update the classic BibTeX fixture manifest'
  if [[ ! -f "$archive" || ! -f "${source_dir}/configure" ]]; then
    [[ "$cache_root" == "${repo_root}/third_party/texlive-source" ]] || \
      die "selected TeX Live cache is incomplete: ${cache_root}"
    run_command 'Acquiring pinned TeX Live source for classic BibTeX' \
      "${repo_root}/scripts/build-trip-initex.sh"
  fi
  [[ "$(sha512_file "$archive")" == "$expected_archive_sha512" ]] || \
    die "pinned TeX Live archive identity mismatch: ${archive}"
  [[ "$(sha256_file "${source_dir}/texk/web2c/bibtex.web")" == \
      "38b9ba09fce5abb6f7ec135a2474b26c0d8c3a8b883df2d1c07072d33bc331ed" ]] || \
    die 'bibtex.web identity mismatch'
  [[ "$(sha256_file "${source_dir}/texk/web2c/bibtex.ch")" == \
      "9bffb931a113278d3c9304248a70b47f2576f7ee86fe6c1ae2160865ed0ea716" ]] || \
    die 'bibtex.ch identity mismatch'
  [[ "$(sha256_file "${source_dir}/texk/kpathsea/texmf.cnf")" == \
      "75cc5499ea9d15d1cf68722e75c846155fac55f1bbc2f0ca102ff5d423f49b29" ]] || \
    die 'classic BibTeX texmf.cnf identity mismatch'

  if [[ ! -f "${build_dir}/texk/web2c/Makefile" ]]; then
    [[ "$cache_root" == "${repo_root}/third_party/texlive-source" ]] || \
      die "selected TeX Live cache has no configured Web2C build: ${cache_root}"
    run_command 'Configuring pinned Web2C build for classic BibTeX' \
      "${repo_root}/scripts/build-trip-initex.sh" --offline
  fi
  run_command 'Building pinned classic BibTeX reference' \
    make -C "${build_dir}/texk/web2c" bibtex
  [[ -x "$executable" ]] || die "classic BibTeX reference was not built: ${executable}"
  [[ "$(sha256_file "${build_dir}/texk/web2c/bibtex.p")" == \
      "a0362ee3ca112207a5a666a5bb89484c4bb8c1a44d99c1ea824767b2eaafec79" ]] || \
    die 'merged bibtex.p identity mismatch'
  [[ "$(sha256_file "${build_dir}/texk/web2c/bibtex.c")" == \
      "848e79f7b29e5a2ad2388ffcfc486399c176f0a2dd2d6e83d55188de532bbc3d" ]] || \
    die 'generated bibtex.c identity mismatch'
  [[ "$(sha256_file "${build_dir}/texk/web2c/bibtex.h")" == \
      "2ffa94f92b6c15b16aad99cc39b587f9e34e98731c911148921a6295b273157a" ]] || \
    die 'generated bibtex.h identity mismatch'
  [[ "$(sha256_file "${build_dir}/texk/web2c/w2c/c-auto.h")" == \
      "20553e51994937db88c411bd5aa39d1e34965309a184f14aae02c19ebded1c1d" ]] || \
    die 'Web2C c-auto.h configuration identity mismatch'
  [[ "$(sha256_file "$executable")" == \
      "fcd33ae491e1adfc84a636015d3840ba49556649c65f3bf2db2fa7d2f948dc7e" ]] || \
    die 'classic BibTeX executable identity mismatch; use the pinned Darwin-arm64 build recorded in the manifest'

  build_fixturegen_once
  run_command 'Running bounded classic BST reference differential generator' \
    "$fixturegen_bin" --classic-bibtex-differential \
      --reference "$executable" --texmfcnf "${source_dir}/texk/kpathsea"

  tmp_root="$(mktemp -d)"
  case_dir="${tmp_root}/smoke"
  mkdir -p "$case_dir"
  cp "${fixture_dir}/smoke.aux" "${fixture_dir}/smoke.bib" \
    "${fixture_dir}/smoke.bst" "$case_dir/"
  set +e
  (
    cd "$case_dir"
    env -i PATH=/usr/bin:/bin LC_ALL=C LANGUAGE=C \
      TEXMFCNF="${source_dir}/texk/kpathsea" BIBINPUTS=. BSTINPUTS=. \
      "$executable" smoke >smoke.terminal 2>&1
  )
  exit_status=$?
  set -e
  [[ "$exit_status" -eq 0 ]] || \
    die "classic BibTeX smoke case exited with status ${exit_status}"
  for file in smoke.bbl smoke.blg smoke.terminal; do
    [[ -f "${case_dir}/${file}" ]] || die "classic BibTeX did not produce ${file}"
    if ! cmp -s "${case_dir}/${file}" "${fixture_dir}/${file}"; then
      cp "${case_dir}/${file}" "${fixture_dir}/${file}.tmp"
      mv "${fixture_dir}/${file}.tmp" "${fixture_dir}/${file}"
      printf 'Classic BibTeX fixture updated: tests/corpus/bibtex/cases/smoke/%s\n' "$file" >&2
    fi
  done
  for style in plain apalike; do
    case_dir="${tmp_root}/${style}"
    mkdir -p "$case_dir"
    cp "${repo_root}/tests/corpus/bibtex/cases/${style}/${style}.aux" \
      "${repo_root}/tests/corpus/bibtex/cases/${style}/references.bib" \
      "${repo_root}/tests/corpus/bibtex/styles/${style}.bst" "$case_dir/"
    (
      cd "$case_dir"
      env -i PATH=/usr/bin:/bin LC_ALL=C LANGUAGE=C \
        TEXMFCNF="${source_dir}/texk/kpathsea" BIBINPUTS=. BSTINPUTS=. \
        "$executable" "$style" >/dev/null
    )
    file="${style}.bbl"
    if ! cmp -s "${case_dir}/${file}" \
      "${repo_root}/tests/corpus/bibtex/cases/${style}/${file}"; then
      cp "${case_dir}/${file}" \
        "${repo_root}/tests/corpus/bibtex/cases/${style}/${file}.tmp"
      mv "${repo_root}/tests/corpus/bibtex/cases/${style}/${file}.tmp" \
        "${repo_root}/tests/corpus/bibtex/cases/${style}/${file}"
      printf 'Classic BibTeX fixture updated: tests/corpus/bibtex/cases/%s/%s\n' \
        "$style" "$file" >&2
    fi
  done
  case_dir="${tmp_root}/xampl"
  mkdir -p "$case_dir"
  cp "${source_dir}/texk/web2c/tests/exampl.aux" "$case_dir/exampl.aux"
  cp "${source_dir}/texk/web2c/tests/xampl.bib" "$case_dir/xampl.bib"
  cp "${repo_root}/tests/corpus/bibtex/styles/apalike.bst" "$case_dir/apalike.bst"
  (
    cd "$case_dir"
    env -i PATH=/usr/bin:/bin LC_ALL=C LANGUAGE=C \
      TEXMFCNF="${source_dir}/texk/kpathsea" BIBINPUTS=. BSTINPUTS=. \
      "$executable" exampl >/dev/null
  )
  for file in exampl.aux xampl.bib exampl.bbl; do
    if ! cmp -s "${case_dir}/${file}" \
      "${repo_root}/tests/corpus/bibtex/cases/xampl/${file}"; then
      cp "${case_dir}/${file}" \
        "${repo_root}/tests/corpus/bibtex/cases/xampl/${file}.tmp"
      mv "${repo_root}/tests/corpus/bibtex/cases/xampl/${file}.tmp" \
        "${repo_root}/tests/corpus/bibtex/cases/xampl/${file}"
      printf 'Classic BibTeX fixture updated: tests/corpus/bibtex/cases/xampl/%s\n' \
        "$file" >&2
    fi
  done
  for case in elsarticle-book elsarticle-article elsarticle-names elsarticle-month ieeetran; do
    case_dir="${tmp_root}/${case}"
    mkdir -p "$case_dir"
    style=elsarticle-num
    if [[ "$case" == "ieeetran" ]]; then
      style=IEEEtran
    fi
    cp "${repo_root}/tests/corpus/bibtex/cases/${case}/${case}.aux" \
      "${repo_root}/tests/corpus/bibtex/cases/${case}/references.bib" \
      "${repo_root}/tests/corpus/bibtex/styles/${style}.bst" "$case_dir/"
    set +e
    (
      cd "$case_dir"
      env -i PATH=/usr/bin:/bin LC_ALL=C LANGUAGE=C \
        TEXMFCNF="${source_dir}/texk/kpathsea" BIBINPUTS=. BSTINPUTS=. \
        "$executable" "$case" >"${case}.terminal" 2>&1
    )
    exit_status=$?
    set -e
    [[ "$exit_status" -eq 0 ]] || \
      die "classic BibTeX real-world case ${case} exited with status ${exit_status}"
    for extension in bbl blg terminal; do
      file="${case}.${extension}"
      [[ -f "${case_dir}/${file}" ]] || die "classic BibTeX did not produce ${file}"
      if ! cmp -s "${case_dir}/${file}" \
        "${repo_root}/tests/corpus/bibtex/cases/${case}/${file}"; then
        cp "${case_dir}/${file}" \
          "${repo_root}/tests/corpus/bibtex/cases/${case}/${file}.tmp"
        mv "${repo_root}/tests/corpus/bibtex/cases/${case}/${file}.tmp" \
          "${repo_root}/tests/corpus/bibtex/cases/${case}/${file}"
        printf 'Classic BibTeX fixture updated: tests/corpus/bibtex/cases/%s/%s\n' \
          "$case" "$file" >&2
      fi
    done
  done
  manifest_tmp="${tmp_root}/manifest.json"
  jq \
    --arg bbl_bytes "$(wc -c < "${fixture_dir}/smoke.bbl" | tr -d ' ')" \
    --arg bbl_sha256 "$(sha256_file "${fixture_dir}/smoke.bbl")" \
    --arg blg_bytes "$(wc -c < "${fixture_dir}/smoke.blg" | tr -d ' ')" \
    --arg blg_sha256 "$(sha256_file "${fixture_dir}/smoke.blg")" \
    --arg terminal_bytes "$(wc -c < "${fixture_dir}/smoke.terminal" | tr -d ' ')" \
    --arg terminal_sha256 "$(sha256_file "${fixture_dir}/smoke.terminal")" \
    --arg plain_bbl_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/plain/plain.bbl" | tr -d ' ')" \
    --arg plain_bbl_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/plain/plain.bbl")" \
    --arg apalike_bbl_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/apalike/apalike.bbl" | tr -d ' ')" \
    --arg apalike_bbl_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/apalike/apalike.bbl")" \
    --arg xampl_aux_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/xampl/exampl.aux" | tr -d ' ')" \
    --arg xampl_aux_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/xampl/exampl.aux")" \
    --arg xampl_bib_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/xampl/xampl.bib" | tr -d ' ')" \
    --arg xampl_bib_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/xampl/xampl.bib")" \
    --arg xampl_bbl_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/xampl/exampl.bbl" | tr -d ' ')" \
    --arg xampl_bbl_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/xampl/exampl.bbl")" \
    --arg elsarticle_book_bbl_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/elsarticle-book/elsarticle-book.bbl" | tr -d ' ')" \
    --arg elsarticle_book_bbl_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/elsarticle-book/elsarticle-book.bbl")" \
    --arg elsarticle_book_blg_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/elsarticle-book/elsarticle-book.blg" | tr -d ' ')" \
    --arg elsarticle_book_blg_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/elsarticle-book/elsarticle-book.blg")" \
    --arg elsarticle_book_terminal_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/elsarticle-book/elsarticle-book.terminal" | tr -d ' ')" \
    --arg elsarticle_book_terminal_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/elsarticle-book/elsarticle-book.terminal")" \
    --arg elsarticle_article_bbl_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/elsarticle-article/elsarticle-article.bbl" | tr -d ' ')" \
    --arg elsarticle_article_bbl_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/elsarticle-article/elsarticle-article.bbl")" \
    --arg elsarticle_article_blg_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/elsarticle-article/elsarticle-article.blg" | tr -d ' ')" \
    --arg elsarticle_article_blg_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/elsarticle-article/elsarticle-article.blg")" \
    --arg elsarticle_article_terminal_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/elsarticle-article/elsarticle-article.terminal" | tr -d ' ')" \
    --arg elsarticle_article_terminal_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/elsarticle-article/elsarticle-article.terminal")" \
    '(.cases[] | select(.name == "smoke") | .files[] | select(.role == "bbl-output")) |=
       (.bytes = ($bbl_bytes | tonumber) | .sha256 = $bbl_sha256) |
     (.cases[] | select(.name == "smoke") | .files[] | select(.role == "blg-output")) |=
       (.bytes = ($blg_bytes | tonumber) | .sha256 = $blg_sha256) |
     (.cases[] | select(.name == "smoke") | .files[] | select(.role == "terminal-output")) |=
       (.bytes = ($terminal_bytes | tonumber) | .sha256 = $terminal_sha256) |
     (.standard_style_execution_cases[] | select(.name == "plain") | .files[] |
       select(.path == "cases/plain/plain.bbl")) |=
       (.bytes = ($plain_bbl_bytes | tonumber) | .sha256 = $plain_bbl_sha256) |
     (.standard_style_execution_cases[] | select(.name == "apalike") | .files[] |
       select(.path == "cases/apalike/apalike.bbl")) |=
       (.bytes = ($apalike_bbl_bytes | tonumber) | .sha256 = $apalike_bbl_sha256) |
     (.standard_style_execution_cases[] | select(.name == "xampl") | .files[] |
       select(.path == "cases/xampl/exampl.aux")) |=
       (.bytes = ($xampl_aux_bytes | tonumber) | .sha256 = $xampl_aux_sha256) |
     (.standard_style_execution_cases[] | select(.name == "xampl") | .files[] |
       select(.path == "cases/xampl/xampl.bib")) |=
       (.bytes = ($xampl_bib_bytes | tonumber) | .sha256 = $xampl_bib_sha256) |
     (.standard_style_execution_cases[] | select(.name == "xampl") | .files[] |
       select(.path == "cases/xampl/exampl.bbl")) |=
       (.bytes = ($xampl_bbl_bytes | tonumber) | .sha256 = $xampl_bbl_sha256) |
     (.real_world_execution_cases[] | select(.name == "elsarticle-book") | .files[] |
       select(.path == "cases/elsarticle-book/elsarticle-book.bbl")) |=
       (.bytes = ($elsarticle_book_bbl_bytes | tonumber) | .sha256 = $elsarticle_book_bbl_sha256) |
     (.real_world_execution_cases[] | select(.name == "elsarticle-book") | .files[] |
       select(.path == "cases/elsarticle-book/elsarticle-book.blg")) |=
       (.bytes = ($elsarticle_book_blg_bytes | tonumber) | .sha256 = $elsarticle_book_blg_sha256) |
     (.real_world_execution_cases[] | select(.name == "elsarticle-book") | .files[] |
       select(.path == "cases/elsarticle-book/elsarticle-book.terminal")) |=
       (.bytes = ($elsarticle_book_terminal_bytes | tonumber) | .sha256 = $elsarticle_book_terminal_sha256) |
     (.real_world_execution_cases[] | select(.name == "elsarticle-article") | .files[] |
       select(.path == "cases/elsarticle-article/elsarticle-article.bbl")) |=
       (.bytes = ($elsarticle_article_bbl_bytes | tonumber) | .sha256 = $elsarticle_article_bbl_sha256) |
     (.real_world_execution_cases[] | select(.name == "elsarticle-article") | .files[] |
       select(.path == "cases/elsarticle-article/elsarticle-article.blg")) |=
       (.bytes = ($elsarticle_article_blg_bytes | tonumber) | .sha256 = $elsarticle_article_blg_sha256) |
     (.real_world_execution_cases[] | select(.name == "elsarticle-article") | .files[] |
       select(.path == "cases/elsarticle-article/elsarticle-article.terminal")) |=
       (.bytes = ($elsarticle_article_terminal_bytes | tonumber) | .sha256 = $elsarticle_article_terminal_sha256)' \
    "${repo_root}/tests/corpus/bibtex/manifest.json" > "$manifest_tmp"
  mv "$manifest_tmp" "${repo_root}/tests/corpus/bibtex/manifest.json"
  for case in elsarticle-names elsarticle-month ieeetran; do
    jq \
      --arg case "$case" \
      --arg bbl_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/${case}/${case}.bbl" | tr -d ' ')" \
      --arg bbl_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/${case}/${case}.bbl")" \
      --arg blg_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/${case}/${case}.blg" | tr -d ' ')" \
      --arg blg_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/${case}/${case}.blg")" \
      --arg terminal_bytes "$(wc -c < "${repo_root}/tests/corpus/bibtex/cases/${case}/${case}.terminal" | tr -d ' ')" \
      --arg terminal_sha256 "$(sha256_file "${repo_root}/tests/corpus/bibtex/cases/${case}/${case}.terminal")" \
      '(.real_world_execution_cases[] | select(.name == $case) | .files[] |
         select(.role == "bbl-output")) |=
         (.bytes = ($bbl_bytes | tonumber) | .sha256 = $bbl_sha256) |
       (.real_world_execution_cases[] | select(.name == $case) | .files[] |
         select(.role == "blg-output")) |=
         (.bytes = ($blg_bytes | tonumber) | .sha256 = $blg_sha256) |
       (.real_world_execution_cases[] | select(.name == $case) | .files[] |
         select(.role == "terminal-output")) |=
         (.bytes = ($terminal_bytes | tonumber) | .sha256 = $terminal_sha256)' \
      "${repo_root}/tests/corpus/bibtex/manifest.json" > "$manifest_tmp"
    mv "$manifest_tmp" "${repo_root}/tests/corpus/bibtex/manifest.json"
  done
  rm -rf "$tmp_root"
  run_command 'Validating pinned classic BibTeX fixtures and inventory' \
    cargo test -p bib-engine --test it classic_fixture_manifest_and_inventory_are_complete_and_pinned
}

regen_area() {
  local area="$1"
  is_known_area "$area" || die "unknown fixture area: ${area}"
  if is_text_area "$area"; then
    regen_text_area "$area"
  elif is_dvi_area "$area"; then
    regen_dvi_area "$area"
  elif [[ "$area" == "$pdf_area" ]]; then
    regen_pdf_area
  elif [[ "$area" == "$e2e_area" ]]; then
    regen_e2e_area
  elif [[ "$area" == "$bib_area" ]]; then
    regen_bib_area
  elif [[ "$area" == "$bibtex_area" ]]; then
    regen_bibtex_area
  else
    run_fonts_live_check
  fi
}

case_area_from_arg() {
  local spec="$1"
  printf '%s\n' "${spec%%/*}"
}

case_name_from_arg() {
  local spec="$1"
  local name="${spec#*/}"
  name="${name%.tex}"
  name="${name%.expected.dvi}"
  name="${name%.expected.log}"
  name="${name%.expected.tokens}"
  name="${name%.expected.ref}"
  name="${name%.expected.out}"
  name="${name%.expected.effects}"
  name="${name%.expected.specials}"
  printf '%s\n' "$name"
}

regen_case() {
  local area="$1"
  local case="$2"
  local command_string
  is_known_area "$area" || die "unknown fixture area: ${area}"
  if is_dvi_area "$area"; then
    regen_dvi_case "$area" "$case"
    validate_dvi_area "$area"
  elif [[ "$area" == "$e2e_area" ]]; then
    regen_e2e_case "$case"
  elif [[ "$area" == "$pdf_area" ]]; then
    build_fixturegen_once
    build_umber_once
    run_command "Regenerating pdf/${case} fixtures" \
      env UMBER_BIN="$umber_bin" "$fixturegen_bin" --case pdf "$case"
    command_string="$(test_command_for_area pdf)"
    # shellcheck disable=SC2086
    run_command 'Validating hermetic PDF parity fixtures' $command_string
  elif [[ "$area" == "$bib_area" ]]; then
    die '--case is not meaningful for the pinned bibliography fixture set'
  elif [[ "$area" == "$bibtex_area" ]]; then
    [[ "$case" == "smoke" ]] || die "unknown classic BibTeX fixture case: ${case}"
    regen_bibtex_area
  elif is_text_area "$area"; then
    printf 'Regenerating text area %s for requested case %s\n' "$area" "$case" >&2
    build_fixturegen_once
    if fixturegen_needs_umber "$area"; then
      build_umber_once
    fi
    run_command "Regenerating ${area}/${case} fixture" \
      env UMBER_BIN="$umber_bin" "$fixturegen_bin" --case "$area" "$case"
    command_string="$(test_command_for_area "$area")"
    # shellcheck disable=SC2086
    run_command "Validating ${area} fixtures" $command_string
  else
    die "--case is not meaningful for the fonts live check"
  fi
}

incremental_specs() {
  {
    git diff --name-only -- tests/corpus
    git diff --name-only --cached -- tests/corpus
    git ls-files --others --exclude-standard -- tests/corpus
  } | sort -u
}

regen_incremental() {
  local path
  local area
  local file
  local stem
  local case_specs_file
  local area_specs_file
  local spec

  case_specs_file="$(mktemp)"
  area_specs_file="$(mktemp)"

  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    case "$path" in
      tests/corpus/*/*)
        area="${path#tests/corpus/}"
        area="${area%%/*}"
        file="$(basename "$path")"
        if ! is_known_area "$area"; then
          continue
        fi
        case "$file" in
          *.tex)
            stem="${file%.tex}"
            printf '%s/%s\n' "$area" "$stem" >>"$case_specs_file"
            ;;
          *.expected.*)
            stem="${file%%.expected.*}"
            printf '%s/%s\n' "$area" "$stem" >>"$case_specs_file"
            ;;
          *)
            printf '%s\n' "$area" >>"$area_specs_file"
            ;;
        esac
        ;;
    esac
  done < <(incremental_specs)

  if [[ ! -s "$case_specs_file" && ! -s "$area_specs_file" ]]; then
    printf 'No changed fixture sources or expected files found under tests/corpus.\n' >&2
    rm -f "$case_specs_file" "$area_specs_file"
    return
  fi

  while IFS= read -r spec; do
    [[ -n "$spec" ]] || continue
    regen_case "$(case_area_from_arg "$spec")" "$(case_name_from_arg "$spec")"
  done < <(sort -u "$case_specs_file")

  while IFS= read -r area; do
    [[ -n "$area" ]] || continue
    regen_area "$area"
  done < <(sort -u "$area_specs_file")

  rm -f "$case_specs_file" "$area_specs_file"
}

mode=""
area_arg=""
case_area=""
case_name=""

if [[ "$#" -eq 0 ]]; then
  usage
  exit 2
fi

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    --incremental)
      [[ -z "$mode" ]] || die "choose exactly one mode"
      mode="incremental"
      shift
      ;;
    --all)
      [[ -z "$mode" ]] || die "choose exactly one mode"
      mode="all"
      shift
      ;;
    --area)
      [[ -z "$mode" ]] || die "choose exactly one mode"
      [[ "$#" -ge 2 ]] || die "missing area after --area"
      mode="area"
      area_arg="$2"
      shift 2
      ;;
    --case)
      [[ -z "$mode" ]] || die "choose exactly one mode"
      [[ "$#" -ge 2 ]] || die "missing case after --case"
      mode="case"
      if [[ "$2" == */* ]]; then
        case_area="$(case_area_from_arg "$2")"
        case_name="$(case_name_from_arg "$2")"
        shift 2
      else
        [[ "$#" -ge 3 ]] || die "--case requires AREA CASE or AREA/CASE"
        case_area="$2"
        case_name="$(case_name_from_arg "$3")"
        shift 3
      fi
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

case "$mode" in
  incremental)
    regen_incremental
    ;;
  all)
    for area_arg in "${text_areas[@]}"; do
      regen_area "$area_arg"
    done
    for area_arg in "${dvi_areas[@]}"; do
      regen_area "$area_arg"
    done
    regen_area "$pdf_area"
    regen_area "$e2e_area"
    regen_area "$bib_area"
    regen_area "$bibtex_area"
    ;;
  area)
    regen_area "$area_arg"
    ;;
  case)
    [[ -n "$case_area" && -n "$case_name" ]] || die "missing case"
    regen_case "$case_area" "$case_name"
    ;;
  *)
    usage
    exit 2
    ;;
esac
