\catcode92=0
\catcode123=1
\catcode125=2
\catcode36=3
\catcode38=4
\catcode35=6
\catcode94=7
\catcode95=8
\catcode32=10
\catcode37=14
\font\tenrm=cmr10
\font\sevenrm=cmr10 at 7pt
\font\fiverm=cmr10 at 5pt
\font\teni=cmmi10
\font\seveni=cmmi10 at 7pt
\font\fivei=cmmi10 at 5pt
\font\tensy=cmsy10
\font\sevensy=cmsy10 at 7pt
\font\fivesy=cmsy10 at 5pt
\font\tenex=cmex10
\font\sevenex=cmex10 at 7pt
\font\fiveex=cmex10 at 5pt
\textfont0=\tenrm \scriptfont0=\sevenrm \scriptscriptfont0=\fiverm
\textfont1=\teni \scriptfont1=\seveni \scriptscriptfont1=\fivei
\textfont2=\tensy \scriptfont2=\sevensy \scriptscriptfont2=\fivesy
\textfont3=\tenex \scriptfont3=\sevenex \scriptscriptfont3=\fiveex
\skewchar\teni="7F \skewchar\seveni="7F \skewchar\fivei="7F
\skewchar\tensy="30 \skewchar\sevensy="30 \skewchar\fivesy="30
\tenrm
\fam=-1
\count0=1
\hsize=420pt
\vsize=700pt
\topskip=10pt
\maxdepth=4pt
\baselineskip=12pt
\lineskip=1pt
\lineskiplimit=0pt
\parindent=0pt
\parskip=0pt
\parfillskip=0pt
\overfullrule=0pt
\hbadness=10000
\vbadness=10000
\binoppenalty=700
\relpenalty=500
\mathsurround=0pt
\scriptspace=.5pt
\thinmuskip=3mu
\medmuskip=4mu plus 2mu minus 4mu
\thickmuskip=5mu plus 5mu
\delimiterfactor=901
\delimitershortfall=5pt
\nulldelimiterspace=1.2pt
\predisplaypenalty=0
\postdisplaypenalty=0
\abovedisplayskip=12pt plus 3pt minus 9pt
\belowdisplayskip=12pt plus 3pt minus 9pt
\abovedisplayshortskip=0pt plus 3pt
\belowdisplayshortskip=7pt plus 3pt minus 4pt
\output={\shipout\box255\relax}
\mathcode`A="7141 \mathcode`B="7142 \mathcode`C="7143
\mathcode`D="7144 \mathcode`E="7145 \mathcode`F="7146
\mathcode`G="7147 \mathcode`H="7148 \mathcode`I="7149
\mathcode`J="714A \mathcode`K="714B \mathcode`L="714C
\mathcode`M="714D \mathcode`N="714E \mathcode`O="714F
\mathcode`P="7150 \mathcode`Q="7151 \mathcode`R="7152
\mathcode`S="7153 \mathcode`T="7154 \mathcode`U="7155
\mathcode`V="7156 \mathcode`W="7157 \mathcode`X="7158
\mathcode`Y="7159 \mathcode`Z="715A
\mathcode`a="7161 \mathcode`b="7162 \mathcode`c="7163
\mathcode`d="7164 \mathcode`e="7165 \mathcode`f="7166
\mathcode`g="7167 \mathcode`h="7168 \mathcode`i="7169
\mathcode`j="716A \mathcode`k="716B \mathcode`l="716C
\mathcode`m="716D \mathcode`n="716E \mathcode`o="716F
\mathcode`p="7170 \mathcode`q="7171 \mathcode`r="7172
\mathcode`s="7173 \mathcode`t="7174 \mathcode`u="7175
\mathcode`v="7176 \mathcode`w="7177 \mathcode`x="7178
\mathcode`y="7179 \mathcode`z="717A
\mathcode`+="202B
\mathcode`-="2200
\mathcode`=="303D
\mathcode`<="313C
\mathcode`>="313E
\mathcode`*="2203
\mathcode`/="002F
\mathcode`(="4028
\mathcode`)="5029
\mathcode`[="405B
\mathcode`]="505D
\mathcode`,="602C
\mathcode`;="603B
\mathcode`|="026A
\delcode`(="028300
\delcode`)="029301
\delcode`[="05B302
\delcode`]="05D303
\delcode`<="26830A
\delcode`>="26930B
\delcode`/="02F30E
\delcode`|="26A30C
\mathchardef\sumchar="1350
\mathchardef\prodchar="1351
\mathchardef\intchar="1352
\def\MathClass#1#2{\ifcase#1\mathord#2\or\mathop#2\or\mathbin#2\or\mathrel#2\or\mathopen#2\or\mathclose#2\or\mathpunct#2\else\mathinner#2\fi}
\def\Sum{\mathop\sumchar}
\def\Prod{\mathop\prodchar}
\def\Int{\mathop\intchar\nolimits}
\def\Rad#1{\radical"270370 #1}
\def\Hat#1{\mathaccent"705E #1}
\def\Tilde#1{\mathaccent"707E #1}
